// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: client/depositor.proto

package main

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on OpenSecret with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OpenSecret) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OpenSecret with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OpenSecretMultiError, or
// nil if none found.
func (m *OpenSecret) ValidateAll() error {
	return m.validate(true)
}

func (m *OpenSecret) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if _, ok := SecretType_name[int32(m.GetType())]; !ok {
		err := OpenSecretValidationError{
			field:  "Type",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 150 {
		err := OpenSecretValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 150 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := len(m.GetData()); l < 1 || l > 2048 {
		err := OpenSecretValidationError{
			field:  "Data",
			reason: "value length must be between 1 and 2048 bytes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return OpenSecretMultiError(errors)
	}

	return nil
}

// OpenSecretMultiError is an error wrapping multiple validation errors
// returned by OpenSecret.ValidateAll() if the designated constraints aren't met.
type OpenSecretMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OpenSecretMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OpenSecretMultiError) AllErrors() []error { return m }

// OpenSecretValidationError is the validation error returned by
// OpenSecret.Validate if the designated constraints aren't met.
type OpenSecretValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OpenSecretValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OpenSecretValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OpenSecretValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OpenSecretValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OpenSecretValidationError) ErrorName() string { return "OpenSecretValidationError" }

// Error satisfies the builtin error interface
func (e OpenSecretValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOpenSecret.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OpenSecretValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OpenSecretValidationError{}

// Validate checks the field values on Secret with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Secret) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Secret with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in SecretMultiError, or nil if none found.
func (m *Secret) ValidateAll() error {
	return m.validate(true)
}

func (m *Secret) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetEncryptedDek()) != 256 {
		err := SecretValidationError{
			field:  "EncryptedDek",
			reason: "value length must be 256 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := len(m.GetEncryptedData()); l < 16 || l > 2250 {
		err := SecretValidationError{
			field:  "EncryptedData",
			reason: "value length must be between 16 and 2250 bytes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(m.GetNonce()) != 12 {
		err := SecretValidationError{
			field:  "Nonce",
			reason: "value length must be 12 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return SecretMultiError(errors)
	}

	return nil
}

// SecretMultiError is an error wrapping multiple validation errors returned by
// Secret.ValidateAll() if the designated constraints aren't met.
type SecretMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SecretMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SecretMultiError) AllErrors() []error { return m }

// SecretValidationError is the validation error returned by Secret.Validate if
// the designated constraints aren't met.
type SecretValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SecretValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SecretValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SecretValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SecretValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SecretValidationError) ErrorName() string { return "SecretValidationError" }

// Error satisfies the builtin error interface
func (e SecretValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSecret.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SecretValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SecretValidationError{}
