// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package depositor

import (
	"context"
	"github.com/oleshko-g/gophkeeper/internal/db/pgx/queries"
	"sync"
)

// Ensure, that QuerierMock does implement Querier.
// If this is not the case, regenerate this file with moq.
var _ Querier = &QuerierMock{}

// QuerierMock is a mock implementation of Querier.
//
//	func TestSomethingThatUsesQuerier(t *testing.T) {
//
//		// make and configure a mocked Querier
//		mockedQuerier := &QuerierMock{
//			InsertPubKeyFunc: func(ctx context.Context, arg queries.InsertPubKeyParams) error {
//				panic("mock out the InsertPubKey method")
//			},
//		}
//
//		// use mockedQuerier in code that requires Querier
//		// and then make assertions.
//
//	}
type QuerierMock struct {
	// InsertPubKeyFunc mocks the InsertPubKey method.
	InsertPubKeyFunc func(ctx context.Context, arg queries.InsertPubKeyParams) error

	// calls tracks calls to the methods.
	calls struct {
		// InsertPubKey holds details about calls to the InsertPubKey method.
		InsertPubKey []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg queries.InsertPubKeyParams
		}
	}
	lockInsertPubKey sync.RWMutex
}

// InsertPubKey calls InsertPubKeyFunc.
func (mock *QuerierMock) InsertPubKey(ctx context.Context, arg queries.InsertPubKeyParams) error {
	if mock.InsertPubKeyFunc == nil {
		panic("QuerierMock.InsertPubKeyFunc: method is nil but Querier.InsertPubKey was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg queries.InsertPubKeyParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockInsertPubKey.Lock()
	mock.calls.InsertPubKey = append(mock.calls.InsertPubKey, callInfo)
	mock.lockInsertPubKey.Unlock()
	return mock.InsertPubKeyFunc(ctx, arg)
}

// InsertPubKeyCalls gets all the calls that were made to InsertPubKey.
// Check the length with:
//
//	len(mockedQuerier.InsertPubKeyCalls())
func (mock *QuerierMock) InsertPubKeyCalls() []struct {
	Ctx context.Context
	Arg queries.InsertPubKeyParams
} {
	var calls []struct {
		Ctx context.Context
		Arg queries.InsertPubKeyParams
	}
	mock.lockInsertPubKey.RLock()
	calls = mock.calls.InsertPubKey
	mock.lockInsertPubKey.RUnlock()
	return calls
}
