// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package depositor

import (
	"context"
	"github.com/google/uuid"
	"github.com/oleshko-g/gophkeeper/internal/db/pgx/queries"
	"sync"
)

// Ensure, that QuerierMock does implement Querier.
// If this is not the case, regenerate this file with moq.
var _ Querier = &QuerierMock{}

// QuerierMock is a mock implementation of Querier.
//
//	func TestSomethingThatUsesQuerier(t *testing.T) {
//
//		// make and configure a mocked Querier
//		mockedQuerier := &QuerierMock{
//			InsertPubKeyFunc: func(ctx context.Context, arg queries.InsertPubKeyParams) error {
//				panic("mock out the InsertPubKey method")
//			},
//			SelectPubKeyByIDFunc: func(ctx context.Context, id uuid.UUID) (queries.DepositorPubKey, error) {
//				panic("mock out the SelectPubKeyByID method")
//			},
//		}
//
//		// use mockedQuerier in code that requires Querier
//		// and then make assertions.
//
//	}
type QuerierMock struct {
	// InsertPubKeyFunc mocks the InsertPubKey method.
	InsertPubKeyFunc func(ctx context.Context, arg queries.InsertPubKeyParams) error

	// SelectPubKeyByIDFunc mocks the SelectPubKeyByID method.
	SelectPubKeyByIDFunc func(ctx context.Context, id uuid.UUID) (queries.DepositorPubKey, error)

	// calls tracks calls to the methods.
	calls struct {
		// InsertPubKey holds details about calls to the InsertPubKey method.
		InsertPubKey []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg queries.InsertPubKeyParams
		}
		// SelectPubKeyByID holds details about calls to the SelectPubKeyByID method.
		SelectPubKeyByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
	}
	lockInsertPubKey     sync.RWMutex
	lockSelectPubKeyByID sync.RWMutex
}

// InsertPubKey calls InsertPubKeyFunc.
func (mock *QuerierMock) InsertPubKey(ctx context.Context, arg queries.InsertPubKeyParams) error {
	if mock.InsertPubKeyFunc == nil {
		panic("QuerierMock.InsertPubKeyFunc: method is nil but Querier.InsertPubKey was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg queries.InsertPubKeyParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockInsertPubKey.Lock()
	mock.calls.InsertPubKey = append(mock.calls.InsertPubKey, callInfo)
	mock.lockInsertPubKey.Unlock()
	return mock.InsertPubKeyFunc(ctx, arg)
}

// InsertPubKeyCalls gets all the calls that were made to InsertPubKey.
// Check the length with:
//
//	len(mockedQuerier.InsertPubKeyCalls())
func (mock *QuerierMock) InsertPubKeyCalls() []struct {
	Ctx context.Context
	Arg queries.InsertPubKeyParams
} {
	var calls []struct {
		Ctx context.Context
		Arg queries.InsertPubKeyParams
	}
	mock.lockInsertPubKey.RLock()
	calls = mock.calls.InsertPubKey
	mock.lockInsertPubKey.RUnlock()
	return calls
}

// SelectPubKeyByID calls SelectPubKeyByIDFunc.
func (mock *QuerierMock) SelectPubKeyByID(ctx context.Context, id uuid.UUID) (queries.DepositorPubKey, error) {
	if mock.SelectPubKeyByIDFunc == nil {
		panic("QuerierMock.SelectPubKeyByIDFunc: method is nil but Querier.SelectPubKeyByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockSelectPubKeyByID.Lock()
	mock.calls.SelectPubKeyByID = append(mock.calls.SelectPubKeyByID, callInfo)
	mock.lockSelectPubKeyByID.Unlock()
	return mock.SelectPubKeyByIDFunc(ctx, id)
}

// SelectPubKeyByIDCalls gets all the calls that were made to SelectPubKeyByID.
// Check the length with:
//
//	len(mockedQuerier.SelectPubKeyByIDCalls())
func (mock *QuerierMock) SelectPubKeyByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockSelectPubKeyByID.RLock()
	calls = mock.calls.SelectPubKeyByID
	mock.lockSelectPubKeyByID.RUnlock()
	return calls
}
