// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.4-bufbuild-protocompile-easyp-modified
// source: api/v1/api.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PubKey        *string                `protobuf:"bytes,1,opt,name=pub_key,json=pubKey" json:"pub_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetPubKey() string {
	if x != nil && x.PubKey != nil {
		return *x.PubKey
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncryptedId   *string                `protobuf:"bytes,1,opt,name=encrypted_id,json=encryptedId" json:"encrypted_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetEncryptedId() string {
	if x != nil && x.EncryptedId != nil {
		return *x.EncryptedId
	}
	return ""
}

type AuthorizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DecryptedId   *string                `protobuf:"bytes,1,opt,name=decrypted_id,json=decryptedId" json:"decrypted_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_api_v1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorizeRequest) GetDecryptedId() string {
	if x != nil && x.DecryptedId != nil {
		return *x.DecryptedId
	}
	return ""
}

type AuthorizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     *string                `protobuf:"bytes,1,opt,name=auth_token,json=authToken" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_api_v1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{3}
}

func (x *AuthorizeResponse) GetAuthToken() string {
	if x != nil && x.AuthToken != nil {
		return *x.AuthToken
	}
	return ""
}

type DepositSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositSecretRequest) Reset() {
	*x = DepositSecretRequest{}
	mi := &file_api_v1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositSecretRequest) ProtoMessage() {}

func (x *DepositSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositSecretRequest.ProtoReflect.Descriptor instead.
func (*DepositSecretRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{4}
}

func (x *DepositSecretRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type DepositSecretResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DepositedSecretId *UUID                  `protobuf:"bytes,1,opt,name=deposited_secret_id,json=depositedSecretId" json:"deposited_secret_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DepositSecretResponse) Reset() {
	*x = DepositSecretResponse{}
	mi := &file_api_v1_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositSecretResponse) ProtoMessage() {}

func (x *DepositSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositSecretResponse.ProtoReflect.Descriptor instead.
func (*DepositSecretResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{5}
}

func (x *DepositSecretResponse) GetDepositedSecretId() *UUID {
	if x != nil {
		return x.DepositedSecretId
	}
	return nil
}

type ListSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsRequest) Reset() {
	*x = ListSecretsRequest{}
	mi := &file_api_v1_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsRequest) ProtoMessage() {}

func (x *ListSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsRequest.ProtoReflect.Descriptor instead.
func (*ListSecretsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{6}
}

type ListSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretIds     []*UUID                `protobuf:"bytes,1,rep,name=secret_ids,json=secretIds" json:"secret_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsResponse) Reset() {
	*x = ListSecretsResponse{}
	mi := &file_api_v1_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsResponse) ProtoMessage() {}

func (x *ListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{7}
}

func (x *ListSecretsResponse) GetSecretIds() []*UUID {
	if x != nil {
		return x.SecretIds
	}
	return nil
}

type RetrieveSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretId      *UUID                  `protobuf:"bytes,1,opt,name=secret_id,json=secretId" json:"secret_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveSecretRequest) Reset() {
	*x = RetrieveSecretRequest{}
	mi := &file_api_v1_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveSecretRequest) ProtoMessage() {}

func (x *RetrieveSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveSecretRequest.ProtoReflect.Descriptor instead.
func (*RetrieveSecretRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{8}
}

func (x *RetrieveSecretRequest) GetSecretId() *UUID {
	if x != nil {
		return x.SecretId
	}
	return nil
}

type RetrieveSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveSecretResponse) Reset() {
	*x = RetrieveSecretResponse{}
	mi := &file_api_v1_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveSecretResponse) ProtoMessage() {}

func (x *RetrieveSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveSecretResponse.ProtoReflect.Descriptor instead.
func (*RetrieveSecretResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{9}
}

func (x *RetrieveSecretResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type DeleteDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDataRequest) Reset() {
	*x = DeleteDataRequest{}
	mi := &file_api_v1_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataRequest) ProtoMessage() {}

func (x *DeleteDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataRequest.ProtoReflect.Descriptor instead.
func (*DeleteDataRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{10}
}

type DeleteDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDataResponse) Reset() {
	*x = DeleteDataResponse{}
	mi := &file_api_v1_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataResponse) ProtoMessage() {}

func (x *DeleteDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataResponse.ProtoReflect.Descriptor instead.
func (*DeleteDataResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{11}
}

type DownloadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileRequest) Reset() {
	*x = DownloadFileRequest{}
	mi := &file_api_v1_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRequest) ProtoMessage() {}

func (x *DownloadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadFileRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{12}
}

type UUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bytes         []byte                 `protobuf:"bytes,1,opt,name=bytes" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUID) Reset() {
	*x = UUID{}
	mi := &file_api_v1_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{13}
}

func (x *UUID) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

var File_api_v1_api_proto protoreflect.FileDescriptor

const file_api_v1_api_proto_rawDesc = "" +
	"\n" +
	"\x10api/v1/api.proto\x12\x11gophkeeper.api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/api/httpbody.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17validate/validate.proto\"3\n" +
	"\x0fRegisterRequest\x12 \n" +
	"\apub_key\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06pubKey\"5\n" +
	"\x10RegisterResponse\x12!\n" +
	"\fencrypted_id\x18\x01 \x01(\tR\vencryptedId\">\n" +
	"\x10AuthorizeRequest\x12*\n" +
	"\fdecrypted_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\vdecryptedId\"2\n" +
	"\x11AuthorizeResponse\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\"0\n" +
	"\x14DepositSecretRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"`\n" +
	"\x15DepositSecretResponse\x12G\n" +
	"\x13deposited_secret_id\x18\x01 \x01(\v2\x17.gophkeeper.api.v1.UUIDR\x11depositedSecretId\"\x14\n" +
	"\x12ListSecretsRequest\"M\n" +
	"\x13ListSecretsResponse\x126\n" +
	"\n" +
	"secret_ids\x18\x01 \x03(\v2\x17.gophkeeper.api.v1.UUIDR\tsecretIds\"W\n" +
	"\x15RetrieveSecretRequest\x12>\n" +
	"\tsecret_id\x18\x01 \x01(\v2\x17.gophkeeper.api.v1.UUIDB\b\xfaB\x05\x8a\x01\x02\x10\x01R\bsecretId\"2\n" +
	"\x16RetrieveSecretResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"\x13\n" +
	"\x11DeleteDataRequest\"\x14\n" +
	"\x12DeleteDataResponse\"\x15\n" +
	"\x13DownloadFileRequest\"'\n" +
	"\x04UUID\x12\x1f\n" +
	"\x05bytes\x18\x01 \x01(\fB\t\xfaB\x06z\x04\x10\x10\x18\x10R\x05bytes2\xbf\x01\n" +
	"\x10DepositorService\x12S\n" +
	"\bRegister\x12\".gophkeeper.api.v1.RegisterRequest\x1a#.gophkeeper.api.v1.RegisterResponse\x12V\n" +
	"\tAuthorize\x12#.gophkeeper.api.v1.AuthorizeRequest\x1a$.gophkeeper.api.v1.AuthorizeResponse2\xd8\x04\n" +
	"\rKeeperService\x12b\n" +
	"\rDepositSecret\x12'.gophkeeper.api.v1.DepositSecretRequest\x1a(.gophkeeper.api.v1.DepositSecretResponse\x12\\\n" +
	"\vListSecrets\x12%.gophkeeper.api.v1.ListSecretsRequest\x1a&.gophkeeper.api.v1.ListSecretsResponse\x12e\n" +
	"\x0eRetrieveSecret\x12(.gophkeeper.api.v1.RetrieveSecretRequest\x1a).gophkeeper.api.v1.RetrieveSecretResponse\x12Y\n" +
	"\n" +
	"DeleteData\x12$.gophkeeper.api.v1.DeleteDataRequest\x1a%.gophkeeper.api.v1.DeleteDataResponse\x12i\n" +
	"\fDownloadFile\x12&.gophkeeper.api.v1.DownloadFileRequest\x1a\x14.google.api.HttpBody\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/file/download0\x01\x12X\n" +
	"\n" +
	"UploadFile\x12\x14.google.api.HttpBody\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/file/upload(\x01B+Z)github.com/oleshko-g/gophkeeper/api/v1;pbb\beditionsp\xe8\a"

var (
	file_api_v1_api_proto_rawDescOnce sync.Once
	file_api_v1_api_proto_rawDescData []byte
)

func file_api_v1_api_proto_rawDescGZIP() []byte {
	file_api_v1_api_proto_rawDescOnce.Do(func() {
		file_api_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_api_proto_rawDesc), len(file_api_v1_api_proto_rawDesc)))
	})
	return file_api_v1_api_proto_rawDescData
}

var file_api_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_v1_api_proto_goTypes = []any{
	(*RegisterRequest)(nil),        // 0: gophkeeper.api.v1.RegisterRequest
	(*RegisterResponse)(nil),       // 1: gophkeeper.api.v1.RegisterResponse
	(*AuthorizeRequest)(nil),       // 2: gophkeeper.api.v1.AuthorizeRequest
	(*AuthorizeResponse)(nil),      // 3: gophkeeper.api.v1.AuthorizeResponse
	(*DepositSecretRequest)(nil),   // 4: gophkeeper.api.v1.DepositSecretRequest
	(*DepositSecretResponse)(nil),  // 5: gophkeeper.api.v1.DepositSecretResponse
	(*ListSecretsRequest)(nil),     // 6: gophkeeper.api.v1.ListSecretsRequest
	(*ListSecretsResponse)(nil),    // 7: gophkeeper.api.v1.ListSecretsResponse
	(*RetrieveSecretRequest)(nil),  // 8: gophkeeper.api.v1.RetrieveSecretRequest
	(*RetrieveSecretResponse)(nil), // 9: gophkeeper.api.v1.RetrieveSecretResponse
	(*DeleteDataRequest)(nil),      // 10: gophkeeper.api.v1.DeleteDataRequest
	(*DeleteDataResponse)(nil),     // 11: gophkeeper.api.v1.DeleteDataResponse
	(*DownloadFileRequest)(nil),    // 12: gophkeeper.api.v1.DownloadFileRequest
	(*UUID)(nil),                   // 13: gophkeeper.api.v1.UUID
	(*httpbody.HttpBody)(nil),      // 14: google.api.HttpBody
	(*emptypb.Empty)(nil),          // 15: google.protobuf.Empty
}
var file_api_v1_api_proto_depIdxs = []int32{
	13, // 0: gophkeeper.api.v1.DepositSecretResponse.deposited_secret_id:type_name -> gophkeeper.api.v1.UUID
	13, // 1: gophkeeper.api.v1.ListSecretsResponse.secret_ids:type_name -> gophkeeper.api.v1.UUID
	13, // 2: gophkeeper.api.v1.RetrieveSecretRequest.secret_id:type_name -> gophkeeper.api.v1.UUID
	0,  // 3: gophkeeper.api.v1.DepositorService.Register:input_type -> gophkeeper.api.v1.RegisterRequest
	2,  // 4: gophkeeper.api.v1.DepositorService.Authorize:input_type -> gophkeeper.api.v1.AuthorizeRequest
	4,  // 5: gophkeeper.api.v1.KeeperService.DepositSecret:input_type -> gophkeeper.api.v1.DepositSecretRequest
	6,  // 6: gophkeeper.api.v1.KeeperService.ListSecrets:input_type -> gophkeeper.api.v1.ListSecretsRequest
	8,  // 7: gophkeeper.api.v1.KeeperService.RetrieveSecret:input_type -> gophkeeper.api.v1.RetrieveSecretRequest
	10, // 8: gophkeeper.api.v1.KeeperService.DeleteData:input_type -> gophkeeper.api.v1.DeleteDataRequest
	12, // 9: gophkeeper.api.v1.KeeperService.DownloadFile:input_type -> gophkeeper.api.v1.DownloadFileRequest
	14, // 10: gophkeeper.api.v1.KeeperService.UploadFile:input_type -> google.api.HttpBody
	1,  // 11: gophkeeper.api.v1.DepositorService.Register:output_type -> gophkeeper.api.v1.RegisterResponse
	3,  // 12: gophkeeper.api.v1.DepositorService.Authorize:output_type -> gophkeeper.api.v1.AuthorizeResponse
	5,  // 13: gophkeeper.api.v1.KeeperService.DepositSecret:output_type -> gophkeeper.api.v1.DepositSecretResponse
	7,  // 14: gophkeeper.api.v1.KeeperService.ListSecrets:output_type -> gophkeeper.api.v1.ListSecretsResponse
	9,  // 15: gophkeeper.api.v1.KeeperService.RetrieveSecret:output_type -> gophkeeper.api.v1.RetrieveSecretResponse
	11, // 16: gophkeeper.api.v1.KeeperService.DeleteData:output_type -> gophkeeper.api.v1.DeleteDataResponse
	14, // 17: gophkeeper.api.v1.KeeperService.DownloadFile:output_type -> google.api.HttpBody
	15, // 18: gophkeeper.api.v1.KeeperService.UploadFile:output_type -> google.protobuf.Empty
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_v1_api_proto_init() }
func file_api_v1_api_proto_init() {
	if File_api_v1_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_api_proto_rawDesc), len(file_api_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_v1_api_proto_goTypes,
		DependencyIndexes: file_api_v1_api_proto_depIdxs,
		MessageInfos:      file_api_v1_api_proto_msgTypes,
	}.Build()
	File_api_v1_api_proto = out.File
	file_api_v1_api_proto_goTypes = nil
	file_api_v1_api_proto_depIdxs = nil
}
