// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v0.14.1-v0.16.4-bufbuild-protocompile-easyp-modified
// source: api/v1/api.proto

package pb

import (
	context "context"

	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DepositorService_Register_FullMethodName  = "/gophkeeper.api.v1.DepositorService/Register"
	DepositorService_Authorize_FullMethodName = "/gophkeeper.api.v1.DepositorService/Authorize"
)

// DepositorServiceClient is the client API for DepositorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DepositorService is the interface to:
//   - [Register] public keys of the Keeper users
//   - [Authorize] their client apps
type DepositorServiceClient interface {
	// Register registers an anonymous public key and returns encrypted id of the registered pub key and the public key of [KeeperService].
	// The owner of the id can then [Authorize] apps to make requests to [KeeperService]
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Authorize authorizes an app of the registered public key owner's to [KeeperService] and returns an authentication token.
	// The owner of the authentication token can then make requests to [KeeperService]
	Authorize(ctx context.Context, in *AuthorizeRequest, opts ...grpc.CallOption) (*AuthorizeResponse, error)
}

type depositorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDepositorServiceClient(cc grpc.ClientConnInterface) DepositorServiceClient {
	return &depositorServiceClient{cc}
}

func (c *depositorServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, DepositorService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *depositorServiceClient) Authorize(ctx context.Context, in *AuthorizeRequest, opts ...grpc.CallOption) (*AuthorizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizeResponse)
	err := c.cc.Invoke(ctx, DepositorService_Authorize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DepositorServiceServer is the server API for DepositorService service.
// All implementations should embed UnimplementedDepositorServiceServer
// for forward compatibility.
//
// DepositorService is the interface to:
//   - [Register] public keys of the Keeper users
//   - [Authorize] their client apps
type DepositorServiceServer interface {
	// Register registers an anonymous public key and returns encrypted id of the registered pub key and the public key of [KeeperService].
	// The owner of the id can then [Authorize] apps to make requests to [KeeperService]
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Authorize authorizes an app of the registered public key owner's to [KeeperService] and returns an authentication token.
	// The owner of the authentication token can then make requests to [KeeperService]
	Authorize(context.Context, *AuthorizeRequest) (*AuthorizeResponse, error)
}

// UnimplementedDepositorServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDepositorServiceServer struct{}

func (UnimplementedDepositorServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedDepositorServiceServer) Authorize(context.Context, *AuthorizeRequest) (*AuthorizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authorize not implemented")
}
func (UnimplementedDepositorServiceServer) testEmbeddedByValue() {}

// UnsafeDepositorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DepositorServiceServer will
// result in compilation errors.
type UnsafeDepositorServiceServer interface {
	mustEmbedUnimplementedDepositorServiceServer()
}

func RegisterDepositorServiceServer(s grpc.ServiceRegistrar, srv DepositorServiceServer) {
	// If the following call panics, it indicates UnimplementedDepositorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DepositorService_ServiceDesc, srv)
}

func _DepositorService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepositorServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DepositorService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepositorServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepositorService_Authorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepositorServiceServer).Authorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DepositorService_Authorize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepositorServiceServer).Authorize(ctx, req.(*AuthorizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DepositorService_ServiceDesc is the grpc.ServiceDesc for DepositorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DepositorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gophkeeper.api.v1.DepositorService",
	HandlerType: (*DepositorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _DepositorService_Register_Handler,
		},
		{
			MethodName: "Authorize",
			Handler:    _DepositorService_Authorize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/api.proto",
}

const (
	KeeperService_DepositSecret_FullMethodName = "/gophkeeper.api.v1.KeeperService/DepositSecret"
	KeeperService_ListSecrets_FullMethodName   = "/gophkeeper.api.v1.KeeperService/ListSecrets"
	KeeperService_DownloadData_FullMethodName  = "/gophkeeper.api.v1.KeeperService/DownloadData"
	KeeperService_DeleteData_FullMethodName    = "/gophkeeper.api.v1.KeeperService/DeleteData"
	KeeperService_DownloadFile_FullMethodName  = "/gophkeeper.api.v1.KeeperService/DownloadFile"
	KeeperService_UploadFile_FullMethodName    = "/gophkeeper.api.v1.KeeperService/UploadFile"
)

// KeeperServiceClient is the client API for KeeperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KeeperService is the service that deposits and retrieves secrets.
type KeeperServiceClient interface {
	// DepositSecret deposits a secret into the Keeper.
	DepositSecret(ctx context.Context, in *DepositSecretRequest, opts ...grpc.CallOption) (*DepositSecretResponse, error)
	// ListSecrets lists the deposited secrets of the authenticated user.
	ListSecrets(ctx context.Context, in *ListSecretsRequest, opts ...grpc.CallOption) (*ListSecretsResponse, error)
	// DownloadData downloads the [Upload]ed data
	DownloadData(ctx context.Context, in *DownloadDataRequest, opts ...grpc.CallOption) (*DownloadDataResponse, error)
	// DeleteData deletes the [Upload]ed data from the [KeeperService]
	DeleteData(ctx context.Context, in *DeleteDataRequest, opts ...grpc.CallOption) (*DeleteDataResponse, error)
	// DownloadFile downloads a file from the [KeeperService]
	DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[httpbody.HttpBody], error)
	// UploadFile uploads a file to the [KeeperService]
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[httpbody.HttpBody, emptypb.Empty], error)
}

type keeperServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeeperServiceClient(cc grpc.ClientConnInterface) KeeperServiceClient {
	return &keeperServiceClient{cc}
}

func (c *keeperServiceClient) DepositSecret(ctx context.Context, in *DepositSecretRequest, opts ...grpc.CallOption) (*DepositSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepositSecretResponse)
	err := c.cc.Invoke(ctx, KeeperService_DepositSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperServiceClient) ListSecrets(ctx context.Context, in *ListSecretsRequest, opts ...grpc.CallOption) (*ListSecretsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSecretsResponse)
	err := c.cc.Invoke(ctx, KeeperService_ListSecrets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperServiceClient) DownloadData(ctx context.Context, in *DownloadDataRequest, opts ...grpc.CallOption) (*DownloadDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadDataResponse)
	err := c.cc.Invoke(ctx, KeeperService_DownloadData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperServiceClient) DeleteData(ctx context.Context, in *DeleteDataRequest, opts ...grpc.CallOption) (*DeleteDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDataResponse)
	err := c.cc.Invoke(ctx, KeeperService_DeleteData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperServiceClient) DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[httpbody.HttpBody], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KeeperService_ServiceDesc.Streams[0], KeeperService_DownloadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadFileRequest, httpbody.HttpBody]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KeeperService_DownloadFileClient = grpc.ServerStreamingClient[httpbody.HttpBody]

func (c *keeperServiceClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[httpbody.HttpBody, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KeeperService_ServiceDesc.Streams[1], KeeperService_UploadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[httpbody.HttpBody, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KeeperService_UploadFileClient = grpc.ClientStreamingClient[httpbody.HttpBody, emptypb.Empty]

// KeeperServiceServer is the server API for KeeperService service.
// All implementations should embed UnimplementedKeeperServiceServer
// for forward compatibility.
//
// KeeperService is the service that deposits and retrieves secrets.
type KeeperServiceServer interface {
	// DepositSecret deposits a secret into the Keeper.
	DepositSecret(context.Context, *DepositSecretRequest) (*DepositSecretResponse, error)
	// ListSecrets lists the deposited secrets of the authenticated user.
	ListSecrets(context.Context, *ListSecretsRequest) (*ListSecretsResponse, error)
	// DownloadData downloads the [Upload]ed data
	DownloadData(context.Context, *DownloadDataRequest) (*DownloadDataResponse, error)
	// DeleteData deletes the [Upload]ed data from the [KeeperService]
	DeleteData(context.Context, *DeleteDataRequest) (*DeleteDataResponse, error)
	// DownloadFile downloads a file from the [KeeperService]
	DownloadFile(*DownloadFileRequest, grpc.ServerStreamingServer[httpbody.HttpBody]) error
	// UploadFile uploads a file to the [KeeperService]
	UploadFile(grpc.ClientStreamingServer[httpbody.HttpBody, emptypb.Empty]) error
}

// UnimplementedKeeperServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeeperServiceServer struct{}

func (UnimplementedKeeperServiceServer) DepositSecret(context.Context, *DepositSecretRequest) (*DepositSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DepositSecret not implemented")
}
func (UnimplementedKeeperServiceServer) ListSecrets(context.Context, *ListSecretsRequest) (*ListSecretsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSecrets not implemented")
}
func (UnimplementedKeeperServiceServer) DownloadData(context.Context, *DownloadDataRequest) (*DownloadDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadData not implemented")
}
func (UnimplementedKeeperServiceServer) DeleteData(context.Context, *DeleteDataRequest) (*DeleteDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteData not implemented")
}
func (UnimplementedKeeperServiceServer) DownloadFile(*DownloadFileRequest, grpc.ServerStreamingServer[httpbody.HttpBody]) error {
	return status.Error(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedKeeperServiceServer) UploadFile(grpc.ClientStreamingServer[httpbody.HttpBody, emptypb.Empty]) error {
	return status.Error(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedKeeperServiceServer) testEmbeddedByValue() {}

// UnsafeKeeperServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeeperServiceServer will
// result in compilation errors.
type UnsafeKeeperServiceServer interface {
	mustEmbedUnimplementedKeeperServiceServer()
}

func RegisterKeeperServiceServer(s grpc.ServiceRegistrar, srv KeeperServiceServer) {
	// If the following call panics, it indicates UnimplementedKeeperServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeeperService_ServiceDesc, srv)
}

func _KeeperService_DepositSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).DepositSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_DepositSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).DepositSecret(ctx, req.(*DepositSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeeperService_ListSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSecretsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).ListSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_ListSecrets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).ListSecrets(ctx, req.(*ListSecretsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeeperService_DownloadData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).DownloadData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_DownloadData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).DownloadData(ctx, req.(*DownloadDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeeperService_DeleteData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).DeleteData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_DeleteData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).DeleteData(ctx, req.(*DeleteDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeeperService_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KeeperServiceServer).DownloadFile(m, &grpc.GenericServerStream[DownloadFileRequest, httpbody.HttpBody]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KeeperService_DownloadFileServer = grpc.ServerStreamingServer[httpbody.HttpBody]

func _KeeperService_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KeeperServiceServer).UploadFile(&grpc.GenericServerStream[httpbody.HttpBody, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KeeperService_UploadFileServer = grpc.ClientStreamingServer[httpbody.HttpBody, emptypb.Empty]

// KeeperService_ServiceDesc is the grpc.ServiceDesc for KeeperService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeeperService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gophkeeper.api.v1.KeeperService",
	HandlerType: (*KeeperServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DepositSecret",
			Handler:    _KeeperService_DepositSecret_Handler,
		},
		{
			MethodName: "ListSecrets",
			Handler:    _KeeperService_ListSecrets_Handler,
		},
		{
			MethodName: "DownloadData",
			Handler:    _KeeperService_DownloadData_Handler,
		},
		{
			MethodName: "DeleteData",
			Handler:    _KeeperService_DeleteData_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadFile",
			Handler:       _KeeperService_DownloadFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadFile",
			Handler:       _KeeperService_UploadFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/v1/api.proto",
}
