// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package storage

import (
	"context"
	"sync"
)

// Ensure, that DepositorMock does implement Depositor.
// If this is not the case, regenerate this file with moq.
var _ Depositor = &DepositorMock{}

// DepositorMock is a mock implementation of Depositor.
//
//	func TestSomethingThatUsesDepositor(t *testing.T) {
//
//		// make and configure a mocked Depositor
//		mockedDepositor := &DepositorMock{
//			StorePubKeyFunc: func(ctx context.Context, pubKey string) (string, error) {
//				panic("mock out the StorePubKey method")
//			},
//		}
//
//		// use mockedDepositor in code that requires Depositor
//		// and then make assertions.
//
//	}
type DepositorMock struct {
	// StorePubKeyFunc mocks the StorePubKey method.
	StorePubKeyFunc func(ctx context.Context, pubKey string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// StorePubKey holds details about calls to the StorePubKey method.
		StorePubKey []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PubKey is the pubKey argument value.
			PubKey string
		}
	}
	lockStorePubKey sync.RWMutex
}

// StorePubKey calls StorePubKeyFunc.
func (mock *DepositorMock) StorePubKey(ctx context.Context, pubKey string) (string, error) {
	if mock.StorePubKeyFunc == nil {
		panic("DepositorMock.StorePubKeyFunc: method is nil but Depositor.StorePubKey was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		PubKey string
	}{
		Ctx:    ctx,
		PubKey: pubKey,
	}
	mock.lockStorePubKey.Lock()
	mock.calls.StorePubKey = append(mock.calls.StorePubKey, callInfo)
	mock.lockStorePubKey.Unlock()
	return mock.StorePubKeyFunc(ctx, pubKey)
}

// StorePubKeyCalls gets all the calls that were made to StorePubKey.
// Check the length with:
//
//	len(mockedDepositor.StorePubKeyCalls())
func (mock *DepositorMock) StorePubKeyCalls() []struct {
	Ctx    context.Context
	PubKey string
} {
	var calls []struct {
		Ctx    context.Context
		PubKey string
	}
	mock.lockStorePubKey.RLock()
	calls = mock.calls.StorePubKey
	mock.lockStorePubKey.RUnlock()
	return calls
}
