// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package storage

import (
	"context"
	"github.com/oleshko-g/gophkeeper/internal/model/depositor"
	"sync"
)

// Ensure, that DepositorMock does implement Depositor.
// If this is not the case, regenerate this file with moq.
var _ Depositor = &DepositorMock{}

// DepositorMock is a mock implementation of Depositor.
//
//	func TestSomethingThatUsesDepositor(t *testing.T) {
//
//		// make and configure a mocked Depositor
//		mockedDepositor := &DepositorMock{
//			StorePubKeyFunc: func(ctx context.Context, pubKey string) (string, error) {
//				panic("mock out the StorePubKey method")
//			},
//			StoreRefreshTokenFunc: func(contextMoqParam context.Context, refreshToken depositor.RefreshToken) error {
//				panic("mock out the StoreRefreshToken method")
//			},
//		}
//
//		// use mockedDepositor in code that requires Depositor
//		// and then make assertions.
//
//	}
type DepositorMock struct {
	// StorePubKeyFunc mocks the StorePubKey method.
	StorePubKeyFunc func(ctx context.Context, pubKey string) (string, error)

	// StoreRefreshTokenFunc mocks the StoreRefreshToken method.
	StoreRefreshTokenFunc func(contextMoqParam context.Context, refreshToken depositor.RefreshToken) error

	// calls tracks calls to the methods.
	calls struct {
		// StorePubKey holds details about calls to the StorePubKey method.
		StorePubKey []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PubKey is the pubKey argument value.
			PubKey string
		}
		// StoreRefreshToken holds details about calls to the StoreRefreshToken method.
		StoreRefreshToken []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// RefreshToken is the refreshToken argument value.
			RefreshToken depositor.RefreshToken
		}
	}
	lockStorePubKey       sync.RWMutex
	lockStoreRefreshToken sync.RWMutex
}

// StorePubKey calls StorePubKeyFunc.
func (mock *DepositorMock) StorePubKey(ctx context.Context, pubKey string) (string, error) {
	if mock.StorePubKeyFunc == nil {
		panic("DepositorMock.StorePubKeyFunc: method is nil but Depositor.StorePubKey was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		PubKey string
	}{
		Ctx:    ctx,
		PubKey: pubKey,
	}
	mock.lockStorePubKey.Lock()
	mock.calls.StorePubKey = append(mock.calls.StorePubKey, callInfo)
	mock.lockStorePubKey.Unlock()
	return mock.StorePubKeyFunc(ctx, pubKey)
}

// StorePubKeyCalls gets all the calls that were made to StorePubKey.
// Check the length with:
//
//	len(mockedDepositor.StorePubKeyCalls())
func (mock *DepositorMock) StorePubKeyCalls() []struct {
	Ctx    context.Context
	PubKey string
} {
	var calls []struct {
		Ctx    context.Context
		PubKey string
	}
	mock.lockStorePubKey.RLock()
	calls = mock.calls.StorePubKey
	mock.lockStorePubKey.RUnlock()
	return calls
}

// StoreRefreshToken calls StoreRefreshTokenFunc.
func (mock *DepositorMock) StoreRefreshToken(contextMoqParam context.Context, refreshToken depositor.RefreshToken) error {
	if mock.StoreRefreshTokenFunc == nil {
		panic("DepositorMock.StoreRefreshTokenFunc: method is nil but Depositor.StoreRefreshToken was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		RefreshToken    depositor.RefreshToken
	}{
		ContextMoqParam: contextMoqParam,
		RefreshToken:    refreshToken,
	}
	mock.lockStoreRefreshToken.Lock()
	mock.calls.StoreRefreshToken = append(mock.calls.StoreRefreshToken, callInfo)
	mock.lockStoreRefreshToken.Unlock()
	return mock.StoreRefreshTokenFunc(contextMoqParam, refreshToken)
}

// StoreRefreshTokenCalls gets all the calls that were made to StoreRefreshToken.
// Check the length with:
//
//	len(mockedDepositor.StoreRefreshTokenCalls())
func (mock *DepositorMock) StoreRefreshTokenCalls() []struct {
	ContextMoqParam context.Context
	RefreshToken    depositor.RefreshToken
} {
	var calls []struct {
		ContextMoqParam context.Context
		RefreshToken    depositor.RefreshToken
	}
	mock.lockStoreRefreshToken.RLock()
	calls = mock.calls.StoreRefreshToken
	mock.lockStoreRefreshToken.RUnlock()
	return calls
}
