// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package storage

import ()

// Ensure, that DepositorMock does implement Depositor.
// If this is not the case, regenerate this file with moq.
var _ Depositor = &DepositorMock{}

// DepositorMock is a mock implementation of Depositor.
//
//	func TestSomethingThatUsesDepositor(t *testing.T) {
//
//		// make and configure a mocked Depositor
//		mockedDepositor := &DepositorMock{
//		}
//
//		// use mockedDepositor in code that requires Depositor
//		// and then make assertions.
//
//	}
type DepositorMock struct {
	// calls tracks calls to the methods.
	calls struct {
	}
}
