// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package storage

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/oleshko-g/gophkeeper/internal/model/keeper/secret"
	uuidv7 "github.com/oleshko-g/gophkeeper/internal/uuid-v7"
)

// Ensure, that KeeperMock does implement Keeper.
// If this is not the case, regenerate this file with moq.
var _ Keeper = &KeeperMock{}

// KeeperMock is a mock implementation of Keeper.
//
//	func TestSomethingThatUsesKeeper(t *testing.T) {
//
//		// make and configure a mocked Keeper
//		mockedKeeper := &KeeperMock{
//			RemoveSecretFunc: func(ctx context.Context, publicKeyID uuidv7.UUID[uuid.UUID], secretID uuidv7.UUID[uuid.UUID]) error {
//				panic("mock out the RemoveSecret method")
//			},
//			RetrieveSecretFunc: func(ctx context.Context, publicKeyID uuidv7.UUID[uuid.UUID], secretID uuidv7.UUID[uuid.UUID]) (secret.Data, error) {
//				panic("mock out the RetrieveSecret method")
//			},
//			RetrieveSecretIDsFunc: func(ctx context.Context, publicKeyID uuidv7.UUID[uuid.UUID]) (uuid.UUIDs, error) {
//				panic("mock out the RetrieveSecretIDs method")
//			},
//			StoreSecretFunc: func(ctx context.Context, publicKeyID uuidv7.UUID[uuid.UUID], s secret.Data) (*secret.DepositedSecret, error) {
//				panic("mock out the StoreSecret method")
//			},
//		}
//
//		// use mockedKeeper in code that requires Keeper
//		// and then make assertions.
//
//	}
type KeeperMock struct {
	// RemoveSecretFunc mocks the RemoveSecret method.
	RemoveSecretFunc func(ctx context.Context, publicKeyID uuidv7.UUID[uuid.UUID], secretID uuidv7.UUID[uuid.UUID]) error

	// RetrieveSecretFunc mocks the RetrieveSecret method.
	RetrieveSecretFunc func(ctx context.Context, publicKeyID uuidv7.UUID[uuid.UUID], secretID uuidv7.UUID[uuid.UUID]) (secret.Data, error)

	// RetrieveSecretIDsFunc mocks the RetrieveSecretIDs method.
	RetrieveSecretIDsFunc func(ctx context.Context, publicKeyID uuidv7.UUID[uuid.UUID]) (uuid.UUIDs, error)

	// StoreSecretFunc mocks the StoreSecret method.
	StoreSecretFunc func(ctx context.Context, publicKeyID uuidv7.UUID[uuid.UUID], s secret.Data) (*secret.DepositedSecret, error)

	// calls tracks calls to the methods.
	calls struct {
		// RemoveSecret holds details about calls to the RemoveSecret method.
		RemoveSecret []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PublicKeyID is the publicKeyID argument value.
			PublicKeyID uuidv7.UUID[uuid.UUID]
			// SecretID is the secretID argument value.
			SecretID uuidv7.UUID[uuid.UUID]
		}
		// RetrieveSecret holds details about calls to the RetrieveSecret method.
		RetrieveSecret []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PublicKeyID is the publicKeyID argument value.
			PublicKeyID uuidv7.UUID[uuid.UUID]
			// SecretID is the secretID argument value.
			SecretID uuidv7.UUID[uuid.UUID]
		}
		// RetrieveSecretIDs holds details about calls to the RetrieveSecretIDs method.
		RetrieveSecretIDs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PublicKeyID is the publicKeyID argument value.
			PublicKeyID uuidv7.UUID[uuid.UUID]
		}
		// StoreSecret holds details about calls to the StoreSecret method.
		StoreSecret []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PublicKeyID is the publicKeyID argument value.
			PublicKeyID uuidv7.UUID[uuid.UUID]
			// S is the s argument value.
			S secret.Data
		}
	}
	lockRemoveSecret      sync.RWMutex
	lockRetrieveSecret    sync.RWMutex
	lockRetrieveSecretIDs sync.RWMutex
	lockStoreSecret       sync.RWMutex
}

// RemoveSecret calls RemoveSecretFunc.
func (mock *KeeperMock) RemoveSecret(ctx context.Context, publicKeyID uuidv7.UUID[uuid.UUID], secretID uuidv7.UUID[uuid.UUID]) error {
	if mock.RemoveSecretFunc == nil {
		panic("KeeperMock.RemoveSecretFunc: method is nil but Keeper.RemoveSecret was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		PublicKeyID uuidv7.UUID[uuid.UUID]
		SecretID    uuidv7.UUID[uuid.UUID]
	}{
		Ctx:         ctx,
		PublicKeyID: publicKeyID,
		SecretID:    secretID,
	}
	mock.lockRemoveSecret.Lock()
	mock.calls.RemoveSecret = append(mock.calls.RemoveSecret, callInfo)
	mock.lockRemoveSecret.Unlock()
	return mock.RemoveSecretFunc(ctx, publicKeyID, secretID)
}

// RemoveSecretCalls gets all the calls that were made to RemoveSecret.
// Check the length with:
//
//	len(mockedKeeper.RemoveSecretCalls())
func (mock *KeeperMock) RemoveSecretCalls() []struct {
	Ctx         context.Context
	PublicKeyID uuidv7.UUID[uuid.UUID]
	SecretID    uuidv7.UUID[uuid.UUID]
} {
	var calls []struct {
		Ctx         context.Context
		PublicKeyID uuidv7.UUID[uuid.UUID]
		SecretID    uuidv7.UUID[uuid.UUID]
	}
	mock.lockRemoveSecret.RLock()
	calls = mock.calls.RemoveSecret
	mock.lockRemoveSecret.RUnlock()
	return calls
}

// RetrieveSecret calls RetrieveSecretFunc.
func (mock *KeeperMock) RetrieveSecret(ctx context.Context, publicKeyID uuidv7.UUID[uuid.UUID], secretID uuidv7.UUID[uuid.UUID]) (secret.Data, error) {
	if mock.RetrieveSecretFunc == nil {
		panic("KeeperMock.RetrieveSecretFunc: method is nil but Keeper.RetrieveSecret was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		PublicKeyID uuidv7.UUID[uuid.UUID]
		SecretID    uuidv7.UUID[uuid.UUID]
	}{
		Ctx:         ctx,
		PublicKeyID: publicKeyID,
		SecretID:    secretID,
	}
	mock.lockRetrieveSecret.Lock()
	mock.calls.RetrieveSecret = append(mock.calls.RetrieveSecret, callInfo)
	mock.lockRetrieveSecret.Unlock()
	return mock.RetrieveSecretFunc(ctx, publicKeyID, secretID)
}

// RetrieveSecretCalls gets all the calls that were made to RetrieveSecret.
// Check the length with:
//
//	len(mockedKeeper.RetrieveSecretCalls())
func (mock *KeeperMock) RetrieveSecretCalls() []struct {
	Ctx         context.Context
	PublicKeyID uuidv7.UUID[uuid.UUID]
	SecretID    uuidv7.UUID[uuid.UUID]
} {
	var calls []struct {
		Ctx         context.Context
		PublicKeyID uuidv7.UUID[uuid.UUID]
		SecretID    uuidv7.UUID[uuid.UUID]
	}
	mock.lockRetrieveSecret.RLock()
	calls = mock.calls.RetrieveSecret
	mock.lockRetrieveSecret.RUnlock()
	return calls
}

// RetrieveSecretIDs calls RetrieveSecretIDsFunc.
func (mock *KeeperMock) RetrieveSecretIDs(ctx context.Context, publicKeyID uuidv7.UUID[uuid.UUID]) (uuid.UUIDs, error) {
	if mock.RetrieveSecretIDsFunc == nil {
		panic("KeeperMock.RetrieveSecretIDsFunc: method is nil but Keeper.RetrieveSecretIDs was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		PublicKeyID uuidv7.UUID[uuid.UUID]
	}{
		Ctx:         ctx,
		PublicKeyID: publicKeyID,
	}
	mock.lockRetrieveSecretIDs.Lock()
	mock.calls.RetrieveSecretIDs = append(mock.calls.RetrieveSecretIDs, callInfo)
	mock.lockRetrieveSecretIDs.Unlock()
	return mock.RetrieveSecretIDsFunc(ctx, publicKeyID)
}

// RetrieveSecretIDsCalls gets all the calls that were made to RetrieveSecretIDs.
// Check the length with:
//
//	len(mockedKeeper.RetrieveSecretIDsCalls())
func (mock *KeeperMock) RetrieveSecretIDsCalls() []struct {
	Ctx         context.Context
	PublicKeyID uuidv7.UUID[uuid.UUID]
} {
	var calls []struct {
		Ctx         context.Context
		PublicKeyID uuidv7.UUID[uuid.UUID]
	}
	mock.lockRetrieveSecretIDs.RLock()
	calls = mock.calls.RetrieveSecretIDs
	mock.lockRetrieveSecretIDs.RUnlock()
	return calls
}

// StoreSecret calls StoreSecretFunc.
func (mock *KeeperMock) StoreSecret(ctx context.Context, publicKeyID uuidv7.UUID[uuid.UUID], s secret.Data) (*secret.DepositedSecret, error) {
	if mock.StoreSecretFunc == nil {
		panic("KeeperMock.StoreSecretFunc: method is nil but Keeper.StoreSecret was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		PublicKeyID uuidv7.UUID[uuid.UUID]
		S           secret.Data
	}{
		Ctx:         ctx,
		PublicKeyID: publicKeyID,
		S:           s,
	}
	mock.lockStoreSecret.Lock()
	mock.calls.StoreSecret = append(mock.calls.StoreSecret, callInfo)
	mock.lockStoreSecret.Unlock()
	return mock.StoreSecretFunc(ctx, publicKeyID, s)
}

// StoreSecretCalls gets all the calls that were made to StoreSecret.
// Check the length with:
//
//	len(mockedKeeper.StoreSecretCalls())
func (mock *KeeperMock) StoreSecretCalls() []struct {
	Ctx         context.Context
	PublicKeyID uuidv7.UUID[uuid.UUID]
	S           secret.Data
} {
	var calls []struct {
		Ctx         context.Context
		PublicKeyID uuidv7.UUID[uuid.UUID]
		S           secret.Data
	}
	mock.lockStoreSecret.RLock()
	calls = mock.calls.StoreSecret
	mock.lockStoreSecret.RUnlock()
	return calls
}
