// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package storage

// Ensure, that KeeperMock does implement Keeper.
// If this is not the case, regenerate this file with moq.
var _ Keeper = &KeeperMock{}

// KeeperMock is a mock implementation of Keeper.
//
//	func TestSomethingThatUsesKeeper(t *testing.T) {
//
//		// make and configure a mocked Keeper
//		mockedKeeper := &KeeperMock{
//		}
//
//		// use mockedKeeper in code that requires Keeper
//		// and then make assertions.
//
//	}
type KeeperMock struct {
	// calls tracks calls to the methods.
	calls struct {
	}
}
