// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DepositorRefreshToken struct {
	ID                pgtype.UUID
	Token             string
	DepositorPubKeyID pgtype.UUID
	IssuedAt          pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
}
