// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package grpc

import (
	"context"
	"sync"

	pb "github.com/oleshko-g/gophkeeper/api/v1"
	"google.golang.org/grpc"
)

// Ensure, that DepositorClientMock does implement DepositorClient.
// If this is not the case, regenerate this file with moq.
var _ DepositorClient = &DepositorClientMock{}

// DepositorClientMock is a mock implementation of DepositorClient.
//
//	func TestSomethingThatUsesDepositorClient(t *testing.T) {
//
//		// make and configure a mocked DepositorClient
//		mockedDepositorClient := &DepositorClientMock{
//			AuthorizeFunc: func(ctx context.Context, in *pb.AuthorizeRequest, opts ...grpc.CallOption) (*pb.AuthorizeResponse, error) {
//				panic("mock out the Authorize method")
//			},
//			RegisterFunc: func(ctx context.Context, in *pb.RegisterRequest, opts ...grpc.CallOption) (*pb.RegisterResponse, error) {
//				panic("mock out the Register method")
//			},
//		}
//
//		// use mockedDepositorClient in code that requires DepositorClient
//		// and then make assertions.
//
//	}
type DepositorClientMock struct {
	// AuthorizeFunc mocks the Authorize method.
	AuthorizeFunc func(ctx context.Context, in *pb.AuthorizeRequest, opts ...grpc.CallOption) (*pb.AuthorizeResponse, error)

	// RegisterFunc mocks the Register method.
	RegisterFunc func(ctx context.Context, in *pb.RegisterRequest, opts ...grpc.CallOption) (*pb.RegisterResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// Authorize holds details about calls to the Authorize method.
		Authorize []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *pb.AuthorizeRequest
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
		// Register holds details about calls to the Register method.
		Register []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *pb.RegisterRequest
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
	}
	lockAuthorize sync.RWMutex
	lockRegister  sync.RWMutex
}

// Authorize calls AuthorizeFunc.
func (mock *DepositorClientMock) Authorize(ctx context.Context, in *pb.AuthorizeRequest, opts ...grpc.CallOption) (*pb.AuthorizeResponse, error) {
	if mock.AuthorizeFunc == nil {
		panic("DepositorClientMock.AuthorizeFunc: method is nil but DepositorClient.Authorize was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		In   *pb.AuthorizeRequest
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}
	mock.lockAuthorize.Lock()
	mock.calls.Authorize = append(mock.calls.Authorize, callInfo)
	mock.lockAuthorize.Unlock()
	return mock.AuthorizeFunc(ctx, in, opts...)
}

// AuthorizeCalls gets all the calls that were made to Authorize.
// Check the length with:
//
//	len(mockedDepositorClient.AuthorizeCalls())
func (mock *DepositorClientMock) AuthorizeCalls() []struct {
	Ctx  context.Context
	In   *pb.AuthorizeRequest
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		In   *pb.AuthorizeRequest
		Opts []grpc.CallOption
	}
	mock.lockAuthorize.RLock()
	calls = mock.calls.Authorize
	mock.lockAuthorize.RUnlock()
	return calls
}

// Register calls RegisterFunc.
func (mock *DepositorClientMock) Register(ctx context.Context, in *pb.RegisterRequest, opts ...grpc.CallOption) (*pb.RegisterResponse, error) {
	if mock.RegisterFunc == nil {
		panic("DepositorClientMock.RegisterFunc: method is nil but DepositorClient.Register was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		In   *pb.RegisterRequest
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}
	mock.lockRegister.Lock()
	mock.calls.Register = append(mock.calls.Register, callInfo)
	mock.lockRegister.Unlock()
	return mock.RegisterFunc(ctx, in, opts...)
}

// RegisterCalls gets all the calls that were made to Register.
// Check the length with:
//
//	len(mockedDepositorClient.RegisterCalls())
func (mock *DepositorClientMock) RegisterCalls() []struct {
	Ctx  context.Context
	In   *pb.RegisterRequest
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		In   *pb.RegisterRequest
		Opts []grpc.CallOption
	}
	mock.lockRegister.RLock()
	calls = mock.calls.Register
	mock.lockRegister.RUnlock()
	return calls
}
