// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package grpc

import (
	"context"
	"sync"

	pb "github.com/oleshko-g/gophkeeper/api/v1"
	"google.golang.org/genproto/googleapis/api/httpbody"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

// Ensure, that KeeperClientMock does implement KeeperClient.
// If this is not the case, regenerate this file with moq.
var _ KeeperClient = &KeeperClientMock{}

// KeeperClientMock is a mock implementation of KeeperClient.
//
//	func TestSomethingThatUsesKeeperClient(t *testing.T) {
//
//		// make and configure a mocked KeeperClient
//		mockedKeeperClient := &KeeperClientMock{
//			DepositSecretFunc: func(ctx context.Context, in *pb.DepositSecretRequest, opts ...grpc.CallOption) (*pb.DepositSecretResponse, error) {
//				panic("mock out the DepositSecret method")
//			},
//			DownloadFileFunc: func(ctx context.Context, in *pb.DownloadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[httpbody.HttpBody], error) {
//				panic("mock out the DownloadFile method")
//			},
//			ListSecretsFunc: func(ctx context.Context, in *pb.ListSecretsRequest, opts ...grpc.CallOption) (*pb.ListSecretsResponse, error) {
//				panic("mock out the ListSecrets method")
//			},
//			PurgeSecretFunc: func(ctx context.Context, in *pb.PurgeSecretRequest, opts ...grpc.CallOption) (*pb.PurgeSecretResponse, error) {
//				panic("mock out the PurgeSecret method")
//			},
//			RetrieveSecretFunc: func(ctx context.Context, in *pb.RetrieveSecretRequest, opts ...grpc.CallOption) (*pb.RetrieveSecretResponse, error) {
//				panic("mock out the RetrieveSecret method")
//			},
//			UploadFileFunc: func(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[httpbody.HttpBody, emptypb.Empty], error) {
//				panic("mock out the UploadFile method")
//			},
//		}
//
//		// use mockedKeeperClient in code that requires KeeperClient
//		// and then make assertions.
//
//	}
type KeeperClientMock struct {
	// DepositSecretFunc mocks the DepositSecret method.
	DepositSecretFunc func(ctx context.Context, in *pb.DepositSecretRequest, opts ...grpc.CallOption) (*pb.DepositSecretResponse, error)

	// DownloadFileFunc mocks the DownloadFile method.
	DownloadFileFunc func(ctx context.Context, in *pb.DownloadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[httpbody.HttpBody], error)

	// ListSecretsFunc mocks the ListSecrets method.
	ListSecretsFunc func(ctx context.Context, in *pb.ListSecretsRequest, opts ...grpc.CallOption) (*pb.ListSecretsResponse, error)

	// PurgeSecretFunc mocks the PurgeSecret method.
	PurgeSecretFunc func(ctx context.Context, in *pb.PurgeSecretRequest, opts ...grpc.CallOption) (*pb.PurgeSecretResponse, error)

	// RetrieveSecretFunc mocks the RetrieveSecret method.
	RetrieveSecretFunc func(ctx context.Context, in *pb.RetrieveSecretRequest, opts ...grpc.CallOption) (*pb.RetrieveSecretResponse, error)

	// UploadFileFunc mocks the UploadFile method.
	UploadFileFunc func(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[httpbody.HttpBody, emptypb.Empty], error)

	// calls tracks calls to the methods.
	calls struct {
		// DepositSecret holds details about calls to the DepositSecret method.
		DepositSecret []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *pb.DepositSecretRequest
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
		// DownloadFile holds details about calls to the DownloadFile method.
		DownloadFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *pb.DownloadFileRequest
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
		// ListSecrets holds details about calls to the ListSecrets method.
		ListSecrets []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *pb.ListSecretsRequest
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
		// PurgeSecret holds details about calls to the PurgeSecret method.
		PurgeSecret []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *pb.PurgeSecretRequest
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
		// RetrieveSecret holds details about calls to the RetrieveSecret method.
		RetrieveSecret []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *pb.RetrieveSecretRequest
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
		// UploadFile holds details about calls to the UploadFile method.
		UploadFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
	}
	lockDepositSecret  sync.RWMutex
	lockDownloadFile   sync.RWMutex
	lockListSecrets    sync.RWMutex
	lockPurgeSecret    sync.RWMutex
	lockRetrieveSecret sync.RWMutex
	lockUploadFile     sync.RWMutex
}

// DepositSecret calls DepositSecretFunc.
func (mock *KeeperClientMock) DepositSecret(ctx context.Context, in *pb.DepositSecretRequest, opts ...grpc.CallOption) (*pb.DepositSecretResponse, error) {
	if mock.DepositSecretFunc == nil {
		panic("KeeperClientMock.DepositSecretFunc: method is nil but KeeperClient.DepositSecret was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		In   *pb.DepositSecretRequest
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}
	mock.lockDepositSecret.Lock()
	mock.calls.DepositSecret = append(mock.calls.DepositSecret, callInfo)
	mock.lockDepositSecret.Unlock()
	return mock.DepositSecretFunc(ctx, in, opts...)
}

// DepositSecretCalls gets all the calls that were made to DepositSecret.
// Check the length with:
//
//	len(mockedKeeperClient.DepositSecretCalls())
func (mock *KeeperClientMock) DepositSecretCalls() []struct {
	Ctx  context.Context
	In   *pb.DepositSecretRequest
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		In   *pb.DepositSecretRequest
		Opts []grpc.CallOption
	}
	mock.lockDepositSecret.RLock()
	calls = mock.calls.DepositSecret
	mock.lockDepositSecret.RUnlock()
	return calls
}

// DownloadFile calls DownloadFileFunc.
func (mock *KeeperClientMock) DownloadFile(ctx context.Context, in *pb.DownloadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[httpbody.HttpBody], error) {
	if mock.DownloadFileFunc == nil {
		panic("KeeperClientMock.DownloadFileFunc: method is nil but KeeperClient.DownloadFile was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		In   *pb.DownloadFileRequest
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}
	mock.lockDownloadFile.Lock()
	mock.calls.DownloadFile = append(mock.calls.DownloadFile, callInfo)
	mock.lockDownloadFile.Unlock()
	return mock.DownloadFileFunc(ctx, in, opts...)
}

// DownloadFileCalls gets all the calls that were made to DownloadFile.
// Check the length with:
//
//	len(mockedKeeperClient.DownloadFileCalls())
func (mock *KeeperClientMock) DownloadFileCalls() []struct {
	Ctx  context.Context
	In   *pb.DownloadFileRequest
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		In   *pb.DownloadFileRequest
		Opts []grpc.CallOption
	}
	mock.lockDownloadFile.RLock()
	calls = mock.calls.DownloadFile
	mock.lockDownloadFile.RUnlock()
	return calls
}

// ListSecrets calls ListSecretsFunc.
func (mock *KeeperClientMock) ListSecrets(ctx context.Context, in *pb.ListSecretsRequest, opts ...grpc.CallOption) (*pb.ListSecretsResponse, error) {
	if mock.ListSecretsFunc == nil {
		panic("KeeperClientMock.ListSecretsFunc: method is nil but KeeperClient.ListSecrets was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		In   *pb.ListSecretsRequest
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}
	mock.lockListSecrets.Lock()
	mock.calls.ListSecrets = append(mock.calls.ListSecrets, callInfo)
	mock.lockListSecrets.Unlock()
	return mock.ListSecretsFunc(ctx, in, opts...)
}

// ListSecretsCalls gets all the calls that were made to ListSecrets.
// Check the length with:
//
//	len(mockedKeeperClient.ListSecretsCalls())
func (mock *KeeperClientMock) ListSecretsCalls() []struct {
	Ctx  context.Context
	In   *pb.ListSecretsRequest
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		In   *pb.ListSecretsRequest
		Opts []grpc.CallOption
	}
	mock.lockListSecrets.RLock()
	calls = mock.calls.ListSecrets
	mock.lockListSecrets.RUnlock()
	return calls
}

// PurgeSecret calls PurgeSecretFunc.
func (mock *KeeperClientMock) PurgeSecret(ctx context.Context, in *pb.PurgeSecretRequest, opts ...grpc.CallOption) (*pb.PurgeSecretResponse, error) {
	if mock.PurgeSecretFunc == nil {
		panic("KeeperClientMock.PurgeSecretFunc: method is nil but KeeperClient.PurgeSecret was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		In   *pb.PurgeSecretRequest
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}
	mock.lockPurgeSecret.Lock()
	mock.calls.PurgeSecret = append(mock.calls.PurgeSecret, callInfo)
	mock.lockPurgeSecret.Unlock()
	return mock.PurgeSecretFunc(ctx, in, opts...)
}

// PurgeSecretCalls gets all the calls that were made to PurgeSecret.
// Check the length with:
//
//	len(mockedKeeperClient.PurgeSecretCalls())
func (mock *KeeperClientMock) PurgeSecretCalls() []struct {
	Ctx  context.Context
	In   *pb.PurgeSecretRequest
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		In   *pb.PurgeSecretRequest
		Opts []grpc.CallOption
	}
	mock.lockPurgeSecret.RLock()
	calls = mock.calls.PurgeSecret
	mock.lockPurgeSecret.RUnlock()
	return calls
}

// RetrieveSecret calls RetrieveSecretFunc.
func (mock *KeeperClientMock) RetrieveSecret(ctx context.Context, in *pb.RetrieveSecretRequest, opts ...grpc.CallOption) (*pb.RetrieveSecretResponse, error) {
	if mock.RetrieveSecretFunc == nil {
		panic("KeeperClientMock.RetrieveSecretFunc: method is nil but KeeperClient.RetrieveSecret was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		In   *pb.RetrieveSecretRequest
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}
	mock.lockRetrieveSecret.Lock()
	mock.calls.RetrieveSecret = append(mock.calls.RetrieveSecret, callInfo)
	mock.lockRetrieveSecret.Unlock()
	return mock.RetrieveSecretFunc(ctx, in, opts...)
}

// RetrieveSecretCalls gets all the calls that were made to RetrieveSecret.
// Check the length with:
//
//	len(mockedKeeperClient.RetrieveSecretCalls())
func (mock *KeeperClientMock) RetrieveSecretCalls() []struct {
	Ctx  context.Context
	In   *pb.RetrieveSecretRequest
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		In   *pb.RetrieveSecretRequest
		Opts []grpc.CallOption
	}
	mock.lockRetrieveSecret.RLock()
	calls = mock.calls.RetrieveSecret
	mock.lockRetrieveSecret.RUnlock()
	return calls
}

// UploadFile calls UploadFileFunc.
func (mock *KeeperClientMock) UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[httpbody.HttpBody, emptypb.Empty], error) {
	if mock.UploadFileFunc == nil {
		panic("KeeperClientMock.UploadFileFunc: method is nil but KeeperClient.UploadFile was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		Opts: opts,
	}
	mock.lockUploadFile.Lock()
	mock.calls.UploadFile = append(mock.calls.UploadFile, callInfo)
	mock.lockUploadFile.Unlock()
	return mock.UploadFileFunc(ctx, opts...)
}

// UploadFileCalls gets all the calls that were made to UploadFile.
// Check the length with:
//
//	len(mockedKeeperClient.UploadFileCalls())
func (mock *KeeperClientMock) UploadFileCalls() []struct {
	Ctx  context.Context
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		Opts []grpc.CallOption
	}
	mock.lockUploadFile.RLock()
	calls = mock.calls.UploadFile
	mock.lockUploadFile.RUnlock()
	return calls
}
