@startuml entities
  hide empty members
  entity depositor_pub_keys {
    * id UUID
    --
    - pub_key string
  }
  entity depositor_apps {
    * id UUID
    --
    - app_name string
    - depositor_pub_key_id UUID
  }

  entity depositor_refresh_tokens {
    * id UUID
    - token string
    - depositor_pub_key_id UUID
    - issued_at datetimez
    + revoked_at datetimez
  }

  entity deposited_data {
    * id UUID
    --
    - depositor_pub_key_id UUID
    - ciphered_data jsob
  }

  entity depositor_app_sessions {
    * id UUID
    --
    - depositor_app_id
    - started_at datetimz
    + expired_at datetimz
  }

  depositor_pub_keys::id ||--o{ deposited_data::depositor_pub_key_id
  depositor_pub_keys::id ||-left-o{ depositor_apps::depositor_pub_key_id
  depositor_pub_keys::id ||-up-|{ depositor_refresh_tokens::depositor_pub_key_id
  depositor_apps::id ||-left-o{ depositor_app_sessions::depositor_app_id

@enduml
