// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.4-bufbuild-protocompile-easyp-modified
// source: client/internal/model/depositor.proto

package model

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecretType int32

const (
	SecretType_SECRET_TYPE_UNSPECIFIED SecretType = 0
	SecretType_SECRET_TYPE_STRING      SecretType = 1
)

// Enum value maps for SecretType.
var (
	SecretType_name = map[int32]string{
		0: "SECRET_TYPE_UNSPECIFIED",
		1: "SECRET_TYPE_STRING",
	}
	SecretType_value = map[string]int32{
		"SECRET_TYPE_UNSPECIFIED": 0,
		"SECRET_TYPE_STRING":      1,
	}
)

func (x SecretType) Enum() *SecretType {
	p := new(SecretType)
	*p = x
	return p
}

func (x SecretType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecretType) Descriptor() protoreflect.EnumDescriptor {
	return file_client_internal_model_depositor_proto_enumTypes[0].Descriptor()
}

func (SecretType) Type() protoreflect.EnumType {
	return &file_client_internal_model_depositor_proto_enumTypes[0]
}

func (x SecretType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecretType.Descriptor instead.
func (SecretType) EnumDescriptor() ([]byte, []int) {
	return file_client_internal_model_depositor_proto_rawDescGZIP(), []int{0}
}

type OpenSecret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *SecretType            `protobuf:"varint,1,opt,name=type,enum=gophkeeper.client.v1.SecretType" json:"type,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSecret) Reset() {
	*x = OpenSecret{}
	mi := &file_client_internal_model_depositor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSecret) ProtoMessage() {}

func (x *OpenSecret) ProtoReflect() protoreflect.Message {
	mi := &file_client_internal_model_depositor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSecret.ProtoReflect.Descriptor instead.
func (*OpenSecret) Descriptor() ([]byte, []int) {
	return file_client_internal_model_depositor_proto_rawDescGZIP(), []int{0}
}

func (x *OpenSecret) GetType() SecretType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *OpenSecret) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *OpenSecret) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Secret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncryptedDek  []byte                 `protobuf:"bytes,1,opt,name=encrypted_dek,json=encryptedDek" json:"encrypted_dek,omitempty"`
	EncryptedData []byte                 `protobuf:"bytes,2,opt,name=encrypted_data,json=encryptedData" json:"encrypted_data,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,3,opt,name=nonce" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_client_internal_model_depositor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_client_internal_model_depositor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_client_internal_model_depositor_proto_rawDescGZIP(), []int{1}
}

func (x *Secret) GetEncryptedDek() []byte {
	if x != nil {
		return x.EncryptedDek
	}
	return nil
}

func (x *Secret) GetEncryptedData() []byte {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

func (x *Secret) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

var File_client_internal_model_depositor_proto protoreflect.FileDescriptor

const file_client_internal_model_depositor_proto_rawDesc = "" +
	"\n" +
	"%client/internal/model/depositor.proto\x12\x14gophkeeper.client.v1\x1a\x17validate/validate.proto\"\x8c\x01\n" +
	"\n" +
	"OpenSecret\x12>\n" +
	"\x04type\x18\x01 \x01(\x0e2 .gophkeeper.client.v1.SecretTypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\x04type\x12\x1e\n" +
	"\x04name\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x96\x01R\x04name\x12\x1e\n" +
	"\x04data\x18\x03 \x01(\fB\n" +
	"\xfaB\az\x05\x10\x01\x18\x80\x10R\x04data\"\x89\x01\n" +
	"\x06Secret\x12-\n" +
	"\rencrypted_dek\x18\x01 \x01(\fB\b\xfaB\x05z\x03h\x80\x02R\fencryptedDek\x121\n" +
	"\x0eencrypted_data\x18\x02 \x01(\fB\n" +
	"\xfaB\az\x05\x10\x10\x18\xca\x11R\rencryptedData\x12\x1d\n" +
	"\x05nonce\x18\x03 \x01(\fB\a\xfaB\x04z\x02h\fR\x05nonce*A\n" +
	"\n" +
	"SecretType\x12\x1b\n" +
	"\x17SECRET_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SECRET_TYPE_STRING\x10\x01B7Z5github.com/oleshko-g/gophkeeper/client/internal/modelb\beditionsp\xe8\a"

var (
	file_client_internal_model_depositor_proto_rawDescOnce sync.Once
	file_client_internal_model_depositor_proto_rawDescData []byte
)

func file_client_internal_model_depositor_proto_rawDescGZIP() []byte {
	file_client_internal_model_depositor_proto_rawDescOnce.Do(func() {
		file_client_internal_model_depositor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_internal_model_depositor_proto_rawDesc), len(file_client_internal_model_depositor_proto_rawDesc)))
	})
	return file_client_internal_model_depositor_proto_rawDescData
}

var file_client_internal_model_depositor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_client_internal_model_depositor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_client_internal_model_depositor_proto_goTypes = []any{
	(SecretType)(0),    // 0: gophkeeper.client.v1.SecretType
	(*OpenSecret)(nil), // 1: gophkeeper.client.v1.OpenSecret
	(*Secret)(nil),     // 2: gophkeeper.client.v1.Secret
}
var file_client_internal_model_depositor_proto_depIdxs = []int32{
	0, // 0: gophkeeper.client.v1.OpenSecret.type:type_name -> gophkeeper.client.v1.SecretType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_client_internal_model_depositor_proto_init() }
func file_client_internal_model_depositor_proto_init() {
	if File_client_internal_model_depositor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_internal_model_depositor_proto_rawDesc), len(file_client_internal_model_depositor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_internal_model_depositor_proto_goTypes,
		DependencyIndexes: file_client_internal_model_depositor_proto_depIdxs,
		EnumInfos:         file_client_internal_model_depositor_proto_enumTypes,
		MessageInfos:      file_client_internal_model_depositor_proto_msgTypes,
	}.Build()
	File_client_internal_model_depositor_proto = out.File
	file_client_internal_model_depositor_proto_goTypes = nil
	file_client_internal_model_depositor_proto_depIdxs = nil
}
