// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service

import (
	"context"
	pb "github.com/oleshko-g/gophkeeper/api/v1"
	"github.com/oleshko-g/gophkeeper/internal/model/depositor"
	"sync"
)

// Ensure, that DepositorMock does implement Depositor.
// If this is not the case, regenerate this file with moq.
var _ Depositor = &DepositorMock{}

// DepositorMock is a mock implementation of Depositor.
//
//	func TestSomethingThatUsesDepositor(t *testing.T) {
//
//		// make and configure a mocked Depositor
//		mockedDepositor := &DepositorMock{
//			AuthorizeFunc: func(contextMoqParam context.Context, authorizeRequest *pb.AuthorizeRequest) (*pb.AuthorizeResponse, error) {
//				panic("mock out the Authorize method")
//			},
//			RegisterFunc: func(contextMoqParam context.Context, registerRequest *pb.RegisterRequest) (*pb.RegisterResponse, error) {
//				panic("mock out the Register method")
//			},
//			ValidateAuthTokenFunc: func(token string) (*depositor.AuthorizedApp, error) {
//				panic("mock out the ValidateAuthToken method")
//			},
//		}
//
//		// use mockedDepositor in code that requires Depositor
//		// and then make assertions.
//
//	}
type DepositorMock struct {
	// AuthorizeFunc mocks the Authorize method.
	AuthorizeFunc func(contextMoqParam context.Context, authorizeRequest *pb.AuthorizeRequest) (*pb.AuthorizeResponse, error)

	// RegisterFunc mocks the Register method.
	RegisterFunc func(contextMoqParam context.Context, registerRequest *pb.RegisterRequest) (*pb.RegisterResponse, error)

	// ValidateAuthTokenFunc mocks the ValidateAuthToken method.
	ValidateAuthTokenFunc func(token string) (*depositor.AuthorizedApp, error)

	// calls tracks calls to the methods.
	calls struct {
		// Authorize holds details about calls to the Authorize method.
		Authorize []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// AuthorizeRequest is the authorizeRequest argument value.
			AuthorizeRequest *pb.AuthorizeRequest
		}
		// Register holds details about calls to the Register method.
		Register []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// RegisterRequest is the registerRequest argument value.
			RegisterRequest *pb.RegisterRequest
		}
		// ValidateAuthToken holds details about calls to the ValidateAuthToken method.
		ValidateAuthToken []struct {
			// Token is the token argument value.
			Token string
		}
	}
	lockAuthorize         sync.RWMutex
	lockRegister          sync.RWMutex
	lockValidateAuthToken sync.RWMutex
}

// Authorize calls AuthorizeFunc.
func (mock *DepositorMock) Authorize(contextMoqParam context.Context, authorizeRequest *pb.AuthorizeRequest) (*pb.AuthorizeResponse, error) {
	if mock.AuthorizeFunc == nil {
		panic("DepositorMock.AuthorizeFunc: method is nil but Depositor.Authorize was just called")
	}
	callInfo := struct {
		ContextMoqParam  context.Context
		AuthorizeRequest *pb.AuthorizeRequest
	}{
		ContextMoqParam:  contextMoqParam,
		AuthorizeRequest: authorizeRequest,
	}
	mock.lockAuthorize.Lock()
	mock.calls.Authorize = append(mock.calls.Authorize, callInfo)
	mock.lockAuthorize.Unlock()
	return mock.AuthorizeFunc(contextMoqParam, authorizeRequest)
}

// AuthorizeCalls gets all the calls that were made to Authorize.
// Check the length with:
//
//	len(mockedDepositor.AuthorizeCalls())
func (mock *DepositorMock) AuthorizeCalls() []struct {
	ContextMoqParam  context.Context
	AuthorizeRequest *pb.AuthorizeRequest
} {
	var calls []struct {
		ContextMoqParam  context.Context
		AuthorizeRequest *pb.AuthorizeRequest
	}
	mock.lockAuthorize.RLock()
	calls = mock.calls.Authorize
	mock.lockAuthorize.RUnlock()
	return calls
}

// Register calls RegisterFunc.
func (mock *DepositorMock) Register(contextMoqParam context.Context, registerRequest *pb.RegisterRequest) (*pb.RegisterResponse, error) {
	if mock.RegisterFunc == nil {
		panic("DepositorMock.RegisterFunc: method is nil but Depositor.Register was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		RegisterRequest *pb.RegisterRequest
	}{
		ContextMoqParam: contextMoqParam,
		RegisterRequest: registerRequest,
	}
	mock.lockRegister.Lock()
	mock.calls.Register = append(mock.calls.Register, callInfo)
	mock.lockRegister.Unlock()
	return mock.RegisterFunc(contextMoqParam, registerRequest)
}

// RegisterCalls gets all the calls that were made to Register.
// Check the length with:
//
//	len(mockedDepositor.RegisterCalls())
func (mock *DepositorMock) RegisterCalls() []struct {
	ContextMoqParam context.Context
	RegisterRequest *pb.RegisterRequest
} {
	var calls []struct {
		ContextMoqParam context.Context
		RegisterRequest *pb.RegisterRequest
	}
	mock.lockRegister.RLock()
	calls = mock.calls.Register
	mock.lockRegister.RUnlock()
	return calls
}

// ValidateAuthToken calls ValidateAuthTokenFunc.
func (mock *DepositorMock) ValidateAuthToken(token string) (*depositor.AuthorizedApp, error) {
	if mock.ValidateAuthTokenFunc == nil {
		panic("DepositorMock.ValidateAuthTokenFunc: method is nil but Depositor.ValidateAuthToken was just called")
	}
	callInfo := struct {
		Token string
	}{
		Token: token,
	}
	mock.lockValidateAuthToken.Lock()
	mock.calls.ValidateAuthToken = append(mock.calls.ValidateAuthToken, callInfo)
	mock.lockValidateAuthToken.Unlock()
	return mock.ValidateAuthTokenFunc(token)
}

// ValidateAuthTokenCalls gets all the calls that were made to ValidateAuthToken.
// Check the length with:
//
//	len(mockedDepositor.ValidateAuthTokenCalls())
func (mock *DepositorMock) ValidateAuthTokenCalls() []struct {
	Token string
} {
	var calls []struct {
		Token string
	}
	mock.lockValidateAuthToken.RLock()
	calls = mock.calls.ValidateAuthToken
	mock.lockValidateAuthToken.RUnlock()
	return calls
}
