// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service

import (
	"context"
	"sync"

	pb "github.com/oleshko-g/gophkeeper/api/v1"
)

// Ensure, that DepositorMock does implement Depositor.
// If this is not the case, regenerate this file with moq.
var _ Depositor = &DepositorMock{}

// DepositorMock is a mock implementation of Depositor.
//
//	func TestSomethingThatUsesDepositor(t *testing.T) {
//
//		// make and configure a mocked Depositor
//		mockedDepositor := &DepositorMock{
//			AuthorizeFunc: func(ctx context.Context, in *AuthorizeRequest) (*AuthorizeResponse, error) {
//				panic("mock out the Authorize method")
//			},
//			ConnectFunc: func(ctx context.Context, in *ConnectRequest) (*ConnectResponse, error) {
//				panic("mock out the Connect method")
//			},
//			RegisterFunc: func(ctx context.Context, in *pb.RegisterRequest) (*pb.RegisterResponse, error) {
//				panic("mock out the Register method")
//			},
//		}
//
//		// use mockedDepositor in code that requires Depositor
//		// and then make assertions.
//
//	}
type DepositorMock struct {
	// AuthorizeFunc mocks the Authorize method.
	AuthorizeFunc func(ctx context.Context, in *AuthorizeRequest) (*AuthorizeResponse, error)

	// ConnectFunc mocks the Connect method.
	ConnectFunc func(ctx context.Context, in *ConnectRequest) (*ConnectResponse, error)

	// RegisterFunc mocks the Register method.
	RegisterFunc func(ctx context.Context, in *pb.RegisterRequest) (*pb.RegisterResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// Authorize holds details about calls to the Authorize method.
		Authorize []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *AuthorizeRequest
		}
		// Connect holds details about calls to the Connect method.
		Connect []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *ConnectRequest
		}
		// Register holds details about calls to the Register method.
		Register []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *pb.RegisterRequest
		}
	}
	lockAuthorize sync.RWMutex
	lockConnect   sync.RWMutex
	lockRegister  sync.RWMutex
}

// Authorize calls AuthorizeFunc.
func (mock *DepositorMock) Authorize(ctx context.Context, in *AuthorizeRequest) (*AuthorizeResponse, error) {
	if mock.AuthorizeFunc == nil {
		panic("DepositorMock.AuthorizeFunc: method is nil but Depositor.Authorize was just called")
	}
	callInfo := struct {
		Ctx context.Context
		In  *AuthorizeRequest
	}{
		Ctx: ctx,
		In:  in,
	}
	mock.lockAuthorize.Lock()
	mock.calls.Authorize = append(mock.calls.Authorize, callInfo)
	mock.lockAuthorize.Unlock()
	return mock.AuthorizeFunc(ctx, in)
}

// AuthorizeCalls gets all the calls that were made to Authorize.
// Check the length with:
//
//	len(mockedDepositor.AuthorizeCalls())
func (mock *DepositorMock) AuthorizeCalls() []struct {
	Ctx context.Context
	In  *AuthorizeRequest
} {
	var calls []struct {
		Ctx context.Context
		In  *AuthorizeRequest
	}
	mock.lockAuthorize.RLock()
	calls = mock.calls.Authorize
	mock.lockAuthorize.RUnlock()
	return calls
}

// Connect calls ConnectFunc.
func (mock *DepositorMock) Connect(ctx context.Context, in *ConnectRequest) (*ConnectResponse, error) {
	if mock.ConnectFunc == nil {
		panic("DepositorMock.ConnectFunc: method is nil but Depositor.Connect was just called")
	}
	callInfo := struct {
		Ctx context.Context
		In  *ConnectRequest
	}{
		Ctx: ctx,
		In:  in,
	}
	mock.lockConnect.Lock()
	mock.calls.Connect = append(mock.calls.Connect, callInfo)
	mock.lockConnect.Unlock()
	return mock.ConnectFunc(ctx, in)
}

// ConnectCalls gets all the calls that were made to Connect.
// Check the length with:
//
//	len(mockedDepositor.ConnectCalls())
func (mock *DepositorMock) ConnectCalls() []struct {
	Ctx context.Context
	In  *ConnectRequest
} {
	var calls []struct {
		Ctx context.Context
		In  *ConnectRequest
	}
	mock.lockConnect.RLock()
	calls = mock.calls.Connect
	mock.lockConnect.RUnlock()
	return calls
}

// Register calls RegisterFunc.
func (mock *DepositorMock) Register(ctx context.Context, in *pb.RegisterRequest) (*pb.RegisterResponse, error) {
	if mock.RegisterFunc == nil {
		panic("DepositorMock.RegisterFunc: method is nil but Depositor.Register was just called")
	}
	callInfo := struct {
		Ctx context.Context
		In  *pb.RegisterRequest
	}{
		Ctx: ctx,
		In:  in,
	}
	mock.lockRegister.Lock()
	mock.calls.Register = append(mock.calls.Register, callInfo)
	mock.lockRegister.Unlock()
	return mock.RegisterFunc(ctx, in)
}

// RegisterCalls gets all the calls that were made to Register.
// Check the length with:
//
//	len(mockedDepositor.RegisterCalls())
func (mock *DepositorMock) RegisterCalls() []struct {
	Ctx context.Context
	In  *pb.RegisterRequest
} {
	var calls []struct {
		Ctx context.Context
		In  *pb.RegisterRequest
	}
	mock.lockRegister.RLock()
	calls = mock.calls.Register
	mock.lockRegister.RUnlock()
	return calls
}
