// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service

import (
	"context"
	pb "github.com/oleshko-g/gophkeeper/api/v1"
	"google.golang.org/genproto/googleapis/api/httpbody"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
	"sync"
)

// Ensure, that KeeperMock does implement Keeper.
// If this is not the case, regenerate this file with moq.
var _ Keeper = &KeeperMock{}

// KeeperMock is a mock implementation of Keeper.
//
//	func TestSomethingThatUsesKeeper(t *testing.T) {
//
//		// make and configure a mocked Keeper
//		mockedKeeper := &KeeperMock{
//			DeleteDataFunc: func(contextMoqParam context.Context, deleteDataRequest *pb.DeleteDataRequest) (*pb.DeleteDataResponse, error) {
//				panic("mock out the DeleteData method")
//			},
//			DepositSecretFunc: func(contextMoqParam context.Context, depositSecretRequest *pb.DepositSecretRequest) (*pb.DepositSecretResponse, error) {
//				panic("mock out the DepositSecret method")
//			},
//			DownloadDataFunc: func(contextMoqParam context.Context, downloadDataRequest *pb.DownloadDataRequest) (*pb.DownloadDataResponse, error) {
//				panic("mock out the DownloadData method")
//			},
//			DownloadFileFunc: func(downloadFileRequest *pb.DownloadFileRequest, serverStreamingServer grpc.ServerStreamingServer[httpbody.HttpBody]) error {
//				panic("mock out the DownloadFile method")
//			},
//			ListDataFunc: func(contextMoqParam context.Context, listDataRequest *pb.ListDataRequest) (*pb.ListDataResponse, error) {
//				panic("mock out the ListData method")
//			},
//			NameFunc: func() string {
//				panic("mock out the Name method")
//			},
//			UploadFileFunc: func(clientStreamingServer grpc.ClientStreamingServer[httpbody.HttpBody, emptypb.Empty]) error {
//				panic("mock out the UploadFile method")
//			},
//		}
//
//		// use mockedKeeper in code that requires Keeper
//		// and then make assertions.
//
//	}
type KeeperMock struct {
	// DeleteDataFunc mocks the DeleteData method.
	DeleteDataFunc func(contextMoqParam context.Context, deleteDataRequest *pb.DeleteDataRequest) (*pb.DeleteDataResponse, error)

	// DepositSecretFunc mocks the DepositSecret method.
	DepositSecretFunc func(contextMoqParam context.Context, depositSecretRequest *pb.DepositSecretRequest) (*pb.DepositSecretResponse, error)

	// DownloadDataFunc mocks the DownloadData method.
	DownloadDataFunc func(contextMoqParam context.Context, downloadDataRequest *pb.DownloadDataRequest) (*pb.DownloadDataResponse, error)

	// DownloadFileFunc mocks the DownloadFile method.
	DownloadFileFunc func(downloadFileRequest *pb.DownloadFileRequest, serverStreamingServer grpc.ServerStreamingServer[httpbody.HttpBody]) error

	// ListDataFunc mocks the ListData method.
	ListDataFunc func(contextMoqParam context.Context, listDataRequest *pb.ListDataRequest) (*pb.ListDataResponse, error)

	// NameFunc mocks the Name method.
	NameFunc func() string

	// UploadFileFunc mocks the UploadFile method.
	UploadFileFunc func(clientStreamingServer grpc.ClientStreamingServer[httpbody.HttpBody, emptypb.Empty]) error

	// calls tracks calls to the methods.
	calls struct {
		// DeleteData holds details about calls to the DeleteData method.
		DeleteData []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// DeleteDataRequest is the deleteDataRequest argument value.
			DeleteDataRequest *pb.DeleteDataRequest
		}
		// DepositSecret holds details about calls to the DepositSecret method.
		DepositSecret []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// DepositSecretRequest is the depositSecretRequest argument value.
			DepositSecretRequest *pb.DepositSecretRequest
		}
		// DownloadData holds details about calls to the DownloadData method.
		DownloadData []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// DownloadDataRequest is the downloadDataRequest argument value.
			DownloadDataRequest *pb.DownloadDataRequest
		}
		// DownloadFile holds details about calls to the DownloadFile method.
		DownloadFile []struct {
			// DownloadFileRequest is the downloadFileRequest argument value.
			DownloadFileRequest *pb.DownloadFileRequest
			// ServerStreamingServer is the serverStreamingServer argument value.
			ServerStreamingServer grpc.ServerStreamingServer[httpbody.HttpBody]
		}
		// ListData holds details about calls to the ListData method.
		ListData []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// ListDataRequest is the listDataRequest argument value.
			ListDataRequest *pb.ListDataRequest
		}
		// Name holds details about calls to the Name method.
		Name []struct {
		}
		// UploadFile holds details about calls to the UploadFile method.
		UploadFile []struct {
			// ClientStreamingServer is the clientStreamingServer argument value.
			ClientStreamingServer grpc.ClientStreamingServer[httpbody.HttpBody, emptypb.Empty]
		}
	}
	lockDeleteData    sync.RWMutex
	lockDepositSecret sync.RWMutex
	lockDownloadData  sync.RWMutex
	lockDownloadFile  sync.RWMutex
	lockListData      sync.RWMutex
	lockName          sync.RWMutex
	lockUploadFile    sync.RWMutex
}

// DeleteData calls DeleteDataFunc.
func (mock *KeeperMock) DeleteData(contextMoqParam context.Context, deleteDataRequest *pb.DeleteDataRequest) (*pb.DeleteDataResponse, error) {
	if mock.DeleteDataFunc == nil {
		panic("KeeperMock.DeleteDataFunc: method is nil but Keeper.DeleteData was just called")
	}
	callInfo := struct {
		ContextMoqParam   context.Context
		DeleteDataRequest *pb.DeleteDataRequest
	}{
		ContextMoqParam:   contextMoqParam,
		DeleteDataRequest: deleteDataRequest,
	}
	mock.lockDeleteData.Lock()
	mock.calls.DeleteData = append(mock.calls.DeleteData, callInfo)
	mock.lockDeleteData.Unlock()
	return mock.DeleteDataFunc(contextMoqParam, deleteDataRequest)
}

// DeleteDataCalls gets all the calls that were made to DeleteData.
// Check the length with:
//
//	len(mockedKeeper.DeleteDataCalls())
func (mock *KeeperMock) DeleteDataCalls() []struct {
	ContextMoqParam   context.Context
	DeleteDataRequest *pb.DeleteDataRequest
} {
	var calls []struct {
		ContextMoqParam   context.Context
		DeleteDataRequest *pb.DeleteDataRequest
	}
	mock.lockDeleteData.RLock()
	calls = mock.calls.DeleteData
	mock.lockDeleteData.RUnlock()
	return calls
}

// DepositSecret calls DepositSecretFunc.
func (mock *KeeperMock) DepositSecret(contextMoqParam context.Context, depositSecretRequest *pb.DepositSecretRequest) (*pb.DepositSecretResponse, error) {
	if mock.DepositSecretFunc == nil {
		panic("KeeperMock.DepositSecretFunc: method is nil but Keeper.DepositSecret was just called")
	}
	callInfo := struct {
		ContextMoqParam      context.Context
		DepositSecretRequest *pb.DepositSecretRequest
	}{
		ContextMoqParam:      contextMoqParam,
		DepositSecretRequest: depositSecretRequest,
	}
	mock.lockDepositSecret.Lock()
	mock.calls.DepositSecret = append(mock.calls.DepositSecret, callInfo)
	mock.lockDepositSecret.Unlock()
	return mock.DepositSecretFunc(contextMoqParam, depositSecretRequest)
}

// DepositSecretCalls gets all the calls that were made to DepositSecret.
// Check the length with:
//
//	len(mockedKeeper.DepositSecretCalls())
func (mock *KeeperMock) DepositSecretCalls() []struct {
	ContextMoqParam      context.Context
	DepositSecretRequest *pb.DepositSecretRequest
} {
	var calls []struct {
		ContextMoqParam      context.Context
		DepositSecretRequest *pb.DepositSecretRequest
	}
	mock.lockDepositSecret.RLock()
	calls = mock.calls.DepositSecret
	mock.lockDepositSecret.RUnlock()
	return calls
}

// DownloadData calls DownloadDataFunc.
func (mock *KeeperMock) DownloadData(contextMoqParam context.Context, downloadDataRequest *pb.DownloadDataRequest) (*pb.DownloadDataResponse, error) {
	if mock.DownloadDataFunc == nil {
		panic("KeeperMock.DownloadDataFunc: method is nil but Keeper.DownloadData was just called")
	}
	callInfo := struct {
		ContextMoqParam     context.Context
		DownloadDataRequest *pb.DownloadDataRequest
	}{
		ContextMoqParam:     contextMoqParam,
		DownloadDataRequest: downloadDataRequest,
	}
	mock.lockDownloadData.Lock()
	mock.calls.DownloadData = append(mock.calls.DownloadData, callInfo)
	mock.lockDownloadData.Unlock()
	return mock.DownloadDataFunc(contextMoqParam, downloadDataRequest)
}

// DownloadDataCalls gets all the calls that were made to DownloadData.
// Check the length with:
//
//	len(mockedKeeper.DownloadDataCalls())
func (mock *KeeperMock) DownloadDataCalls() []struct {
	ContextMoqParam     context.Context
	DownloadDataRequest *pb.DownloadDataRequest
} {
	var calls []struct {
		ContextMoqParam     context.Context
		DownloadDataRequest *pb.DownloadDataRequest
	}
	mock.lockDownloadData.RLock()
	calls = mock.calls.DownloadData
	mock.lockDownloadData.RUnlock()
	return calls
}

// DownloadFile calls DownloadFileFunc.
func (mock *KeeperMock) DownloadFile(downloadFileRequest *pb.DownloadFileRequest, serverStreamingServer grpc.ServerStreamingServer[httpbody.HttpBody]) error {
	if mock.DownloadFileFunc == nil {
		panic("KeeperMock.DownloadFileFunc: method is nil but Keeper.DownloadFile was just called")
	}
	callInfo := struct {
		DownloadFileRequest   *pb.DownloadFileRequest
		ServerStreamingServer grpc.ServerStreamingServer[httpbody.HttpBody]
	}{
		DownloadFileRequest:   downloadFileRequest,
		ServerStreamingServer: serverStreamingServer,
	}
	mock.lockDownloadFile.Lock()
	mock.calls.DownloadFile = append(mock.calls.DownloadFile, callInfo)
	mock.lockDownloadFile.Unlock()
	return mock.DownloadFileFunc(downloadFileRequest, serverStreamingServer)
}

// DownloadFileCalls gets all the calls that were made to DownloadFile.
// Check the length with:
//
//	len(mockedKeeper.DownloadFileCalls())
func (mock *KeeperMock) DownloadFileCalls() []struct {
	DownloadFileRequest   *pb.DownloadFileRequest
	ServerStreamingServer grpc.ServerStreamingServer[httpbody.HttpBody]
} {
	var calls []struct {
		DownloadFileRequest   *pb.DownloadFileRequest
		ServerStreamingServer grpc.ServerStreamingServer[httpbody.HttpBody]
	}
	mock.lockDownloadFile.RLock()
	calls = mock.calls.DownloadFile
	mock.lockDownloadFile.RUnlock()
	return calls
}

// ListData calls ListDataFunc.
func (mock *KeeperMock) ListData(contextMoqParam context.Context, listDataRequest *pb.ListDataRequest) (*pb.ListDataResponse, error) {
	if mock.ListDataFunc == nil {
		panic("KeeperMock.ListDataFunc: method is nil but Keeper.ListData was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		ListDataRequest *pb.ListDataRequest
	}{
		ContextMoqParam: contextMoqParam,
		ListDataRequest: listDataRequest,
	}
	mock.lockListData.Lock()
	mock.calls.ListData = append(mock.calls.ListData, callInfo)
	mock.lockListData.Unlock()
	return mock.ListDataFunc(contextMoqParam, listDataRequest)
}

// ListDataCalls gets all the calls that were made to ListData.
// Check the length with:
//
//	len(mockedKeeper.ListDataCalls())
func (mock *KeeperMock) ListDataCalls() []struct {
	ContextMoqParam context.Context
	ListDataRequest *pb.ListDataRequest
} {
	var calls []struct {
		ContextMoqParam context.Context
		ListDataRequest *pb.ListDataRequest
	}
	mock.lockListData.RLock()
	calls = mock.calls.ListData
	mock.lockListData.RUnlock()
	return calls
}

// Name calls NameFunc.
func (mock *KeeperMock) Name() string {
	if mock.NameFunc == nil {
		panic("KeeperMock.NameFunc: method is nil but Keeper.Name was just called")
	}
	callInfo := struct {
	}{}
	mock.lockName.Lock()
	mock.calls.Name = append(mock.calls.Name, callInfo)
	mock.lockName.Unlock()
	return mock.NameFunc()
}

// NameCalls gets all the calls that were made to Name.
// Check the length with:
//
//	len(mockedKeeper.NameCalls())
func (mock *KeeperMock) NameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockName.RLock()
	calls = mock.calls.Name
	mock.lockName.RUnlock()
	return calls
}

// UploadFile calls UploadFileFunc.
func (mock *KeeperMock) UploadFile(clientStreamingServer grpc.ClientStreamingServer[httpbody.HttpBody, emptypb.Empty]) error {
	if mock.UploadFileFunc == nil {
		panic("KeeperMock.UploadFileFunc: method is nil but Keeper.UploadFile was just called")
	}
	callInfo := struct {
		ClientStreamingServer grpc.ClientStreamingServer[httpbody.HttpBody, emptypb.Empty]
	}{
		ClientStreamingServer: clientStreamingServer,
	}
	mock.lockUploadFile.Lock()
	mock.calls.UploadFile = append(mock.calls.UploadFile, callInfo)
	mock.lockUploadFile.Unlock()
	return mock.UploadFileFunc(clientStreamingServer)
}

// UploadFileCalls gets all the calls that were made to UploadFile.
// Check the length with:
//
//	len(mockedKeeper.UploadFileCalls())
func (mock *KeeperMock) UploadFileCalls() []struct {
	ClientStreamingServer grpc.ClientStreamingServer[httpbody.HttpBody, emptypb.Empty]
} {
	var calls []struct {
		ClientStreamingServer grpc.ClientStreamingServer[httpbody.HttpBody, emptypb.Empty]
	}
	mock.lockUploadFile.RLock()
	calls = mock.calls.UploadFile
	mock.lockUploadFile.RUnlock()
	return calls
}
