// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service

import (
	"context"
	"sync"

	pb "github.com/oleshko-g/gophkeeper/api/v1"
	"google.golang.org/genproto/googleapis/api/httpbody"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

// Ensure, that KeeperMock does implement Keeper.
// If this is not the case, regenerate this file with moq.
var _ Keeper = &KeeperMock{}

// KeeperMock is a mock implementation of Keeper.
//
//	func TestSomethingThatUsesKeeper(t *testing.T) {
//
//		// make and configure a mocked Keeper
//		mockedKeeper := &KeeperMock{
//			DepositSecretFunc: func(contextMoqParam context.Context, depositSecretRequest *pb.DepositSecretRequest) (*pb.DepositSecretResponse, error) {
//				panic("mock out the DepositSecret method")
//			},
//			DownloadFileFunc: func(downloadFileRequest *pb.DownloadFileRequest, serverStreamingServer grpc.ServerStreamingServer[httpbody.HttpBody]) error {
//				panic("mock out the DownloadFile method")
//			},
//			ListSecretsFunc: func(contextMoqParam context.Context, listSecretsRequest *pb.ListSecretsRequest) (*pb.ListSecretsResponse, error) {
//				panic("mock out the ListSecrets method")
//			},
//			NameFunc: func() string {
//				panic("mock out the Name method")
//			},
//			PurgeSecretFunc: func(contextMoqParam context.Context, purgeSecretRequest *pb.PurgeSecretRequest) (*pb.PurgeSecretResponse, error) {
//				panic("mock out the PurgeSecret method")
//			},
//			RetrieveSecretFunc: func(contextMoqParam context.Context, retrieveSecretRequest *pb.RetrieveSecretRequest) (*pb.RetrieveSecretResponse, error) {
//				panic("mock out the RetrieveSecret method")
//			},
//			UploadFileFunc: func(clientStreamingServer grpc.ClientStreamingServer[httpbody.HttpBody, emptypb.Empty]) error {
//				panic("mock out the UploadFile method")
//			},
//		}
//
//		// use mockedKeeper in code that requires Keeper
//		// and then make assertions.
//
//	}
type KeeperMock struct {
	// DepositSecretFunc mocks the DepositSecret method.
	DepositSecretFunc func(contextMoqParam context.Context, depositSecretRequest *pb.DepositSecretRequest) (*pb.DepositSecretResponse, error)

	// DownloadFileFunc mocks the DownloadFile method.
	DownloadFileFunc func(downloadFileRequest *pb.DownloadFileRequest, serverStreamingServer grpc.ServerStreamingServer[httpbody.HttpBody]) error

	// ListSecretsFunc mocks the ListSecrets method.
	ListSecretsFunc func(contextMoqParam context.Context, listSecretsRequest *pb.ListSecretsRequest) (*pb.ListSecretsResponse, error)

	// NameFunc mocks the Name method.
	NameFunc func() string

	// PurgeSecretFunc mocks the PurgeSecret method.
	PurgeSecretFunc func(contextMoqParam context.Context, purgeSecretRequest *pb.PurgeSecretRequest) (*pb.PurgeSecretResponse, error)

	// RetrieveSecretFunc mocks the RetrieveSecret method.
	RetrieveSecretFunc func(contextMoqParam context.Context, retrieveSecretRequest *pb.RetrieveSecretRequest) (*pb.RetrieveSecretResponse, error)

	// UploadFileFunc mocks the UploadFile method.
	UploadFileFunc func(clientStreamingServer grpc.ClientStreamingServer[httpbody.HttpBody, emptypb.Empty]) error

	// calls tracks calls to the methods.
	calls struct {
		// DepositSecret holds details about calls to the DepositSecret method.
		DepositSecret []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// DepositSecretRequest is the depositSecretRequest argument value.
			DepositSecretRequest *pb.DepositSecretRequest
		}
		// DownloadFile holds details about calls to the DownloadFile method.
		DownloadFile []struct {
			// DownloadFileRequest is the downloadFileRequest argument value.
			DownloadFileRequest *pb.DownloadFileRequest
			// ServerStreamingServer is the serverStreamingServer argument value.
			ServerStreamingServer grpc.ServerStreamingServer[httpbody.HttpBody]
		}
		// ListSecrets holds details about calls to the ListSecrets method.
		ListSecrets []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// ListSecretsRequest is the listSecretsRequest argument value.
			ListSecretsRequest *pb.ListSecretsRequest
		}
		// Name holds details about calls to the Name method.
		Name []struct {
		}
		// PurgeSecret holds details about calls to the PurgeSecret method.
		PurgeSecret []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// PurgeSecretRequest is the purgeSecretRequest argument value.
			PurgeSecretRequest *pb.PurgeSecretRequest
		}
		// RetrieveSecret holds details about calls to the RetrieveSecret method.
		RetrieveSecret []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// RetrieveSecretRequest is the retrieveSecretRequest argument value.
			RetrieveSecretRequest *pb.RetrieveSecretRequest
		}
		// UploadFile holds details about calls to the UploadFile method.
		UploadFile []struct {
			// ClientStreamingServer is the clientStreamingServer argument value.
			ClientStreamingServer grpc.ClientStreamingServer[httpbody.HttpBody, emptypb.Empty]
		}
	}
	lockDepositSecret  sync.RWMutex
	lockDownloadFile   sync.RWMutex
	lockListSecrets    sync.RWMutex
	lockName           sync.RWMutex
	lockPurgeSecret    sync.RWMutex
	lockRetrieveSecret sync.RWMutex
	lockUploadFile     sync.RWMutex
}

// DepositSecret calls DepositSecretFunc.
func (mock *KeeperMock) DepositSecret(contextMoqParam context.Context, depositSecretRequest *pb.DepositSecretRequest) (*pb.DepositSecretResponse, error) {
	if mock.DepositSecretFunc == nil {
		panic("KeeperMock.DepositSecretFunc: method is nil but Keeper.DepositSecret was just called")
	}
	callInfo := struct {
		ContextMoqParam      context.Context
		DepositSecretRequest *pb.DepositSecretRequest
	}{
		ContextMoqParam:      contextMoqParam,
		DepositSecretRequest: depositSecretRequest,
	}
	mock.lockDepositSecret.Lock()
	mock.calls.DepositSecret = append(mock.calls.DepositSecret, callInfo)
	mock.lockDepositSecret.Unlock()
	return mock.DepositSecretFunc(contextMoqParam, depositSecretRequest)
}

// DepositSecretCalls gets all the calls that were made to DepositSecret.
// Check the length with:
//
//	len(mockedKeeper.DepositSecretCalls())
func (mock *KeeperMock) DepositSecretCalls() []struct {
	ContextMoqParam      context.Context
	DepositSecretRequest *pb.DepositSecretRequest
} {
	var calls []struct {
		ContextMoqParam      context.Context
		DepositSecretRequest *pb.DepositSecretRequest
	}
	mock.lockDepositSecret.RLock()
	calls = mock.calls.DepositSecret
	mock.lockDepositSecret.RUnlock()
	return calls
}

// DownloadFile calls DownloadFileFunc.
func (mock *KeeperMock) DownloadFile(downloadFileRequest *pb.DownloadFileRequest, serverStreamingServer grpc.ServerStreamingServer[httpbody.HttpBody]) error {
	if mock.DownloadFileFunc == nil {
		panic("KeeperMock.DownloadFileFunc: method is nil but Keeper.DownloadFile was just called")
	}
	callInfo := struct {
		DownloadFileRequest   *pb.DownloadFileRequest
		ServerStreamingServer grpc.ServerStreamingServer[httpbody.HttpBody]
	}{
		DownloadFileRequest:   downloadFileRequest,
		ServerStreamingServer: serverStreamingServer,
	}
	mock.lockDownloadFile.Lock()
	mock.calls.DownloadFile = append(mock.calls.DownloadFile, callInfo)
	mock.lockDownloadFile.Unlock()
	return mock.DownloadFileFunc(downloadFileRequest, serverStreamingServer)
}

// DownloadFileCalls gets all the calls that were made to DownloadFile.
// Check the length with:
//
//	len(mockedKeeper.DownloadFileCalls())
func (mock *KeeperMock) DownloadFileCalls() []struct {
	DownloadFileRequest   *pb.DownloadFileRequest
	ServerStreamingServer grpc.ServerStreamingServer[httpbody.HttpBody]
} {
	var calls []struct {
		DownloadFileRequest   *pb.DownloadFileRequest
		ServerStreamingServer grpc.ServerStreamingServer[httpbody.HttpBody]
	}
	mock.lockDownloadFile.RLock()
	calls = mock.calls.DownloadFile
	mock.lockDownloadFile.RUnlock()
	return calls
}

// ListSecrets calls ListSecretsFunc.
func (mock *KeeperMock) ListSecrets(contextMoqParam context.Context, listSecretsRequest *pb.ListSecretsRequest) (*pb.ListSecretsResponse, error) {
	if mock.ListSecretsFunc == nil {
		panic("KeeperMock.ListSecretsFunc: method is nil but Keeper.ListSecrets was just called")
	}
	callInfo := struct {
		ContextMoqParam    context.Context
		ListSecretsRequest *pb.ListSecretsRequest
	}{
		ContextMoqParam:    contextMoqParam,
		ListSecretsRequest: listSecretsRequest,
	}
	mock.lockListSecrets.Lock()
	mock.calls.ListSecrets = append(mock.calls.ListSecrets, callInfo)
	mock.lockListSecrets.Unlock()
	return mock.ListSecretsFunc(contextMoqParam, listSecretsRequest)
}

// ListSecretsCalls gets all the calls that were made to ListSecrets.
// Check the length with:
//
//	len(mockedKeeper.ListSecretsCalls())
func (mock *KeeperMock) ListSecretsCalls() []struct {
	ContextMoqParam    context.Context
	ListSecretsRequest *pb.ListSecretsRequest
} {
	var calls []struct {
		ContextMoqParam    context.Context
		ListSecretsRequest *pb.ListSecretsRequest
	}
	mock.lockListSecrets.RLock()
	calls = mock.calls.ListSecrets
	mock.lockListSecrets.RUnlock()
	return calls
}

// Name calls NameFunc.
func (mock *KeeperMock) Name() string {
	if mock.NameFunc == nil {
		panic("KeeperMock.NameFunc: method is nil but Keeper.Name was just called")
	}
	callInfo := struct {
	}{}
	mock.lockName.Lock()
	mock.calls.Name = append(mock.calls.Name, callInfo)
	mock.lockName.Unlock()
	return mock.NameFunc()
}

// NameCalls gets all the calls that were made to Name.
// Check the length with:
//
//	len(mockedKeeper.NameCalls())
func (mock *KeeperMock) NameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockName.RLock()
	calls = mock.calls.Name
	mock.lockName.RUnlock()
	return calls
}

// PurgeSecret calls PurgeSecretFunc.
func (mock *KeeperMock) PurgeSecret(contextMoqParam context.Context, purgeSecretRequest *pb.PurgeSecretRequest) (*pb.PurgeSecretResponse, error) {
	if mock.PurgeSecretFunc == nil {
		panic("KeeperMock.PurgeSecretFunc: method is nil but Keeper.PurgeSecret was just called")
	}
	callInfo := struct {
		ContextMoqParam    context.Context
		PurgeSecretRequest *pb.PurgeSecretRequest
	}{
		ContextMoqParam:    contextMoqParam,
		PurgeSecretRequest: purgeSecretRequest,
	}
	mock.lockPurgeSecret.Lock()
	mock.calls.PurgeSecret = append(mock.calls.PurgeSecret, callInfo)
	mock.lockPurgeSecret.Unlock()
	return mock.PurgeSecretFunc(contextMoqParam, purgeSecretRequest)
}

// PurgeSecretCalls gets all the calls that were made to PurgeSecret.
// Check the length with:
//
//	len(mockedKeeper.PurgeSecretCalls())
func (mock *KeeperMock) PurgeSecretCalls() []struct {
	ContextMoqParam    context.Context
	PurgeSecretRequest *pb.PurgeSecretRequest
} {
	var calls []struct {
		ContextMoqParam    context.Context
		PurgeSecretRequest *pb.PurgeSecretRequest
	}
	mock.lockPurgeSecret.RLock()
	calls = mock.calls.PurgeSecret
	mock.lockPurgeSecret.RUnlock()
	return calls
}

// RetrieveSecret calls RetrieveSecretFunc.
func (mock *KeeperMock) RetrieveSecret(contextMoqParam context.Context, retrieveSecretRequest *pb.RetrieveSecretRequest) (*pb.RetrieveSecretResponse, error) {
	if mock.RetrieveSecretFunc == nil {
		panic("KeeperMock.RetrieveSecretFunc: method is nil but Keeper.RetrieveSecret was just called")
	}
	callInfo := struct {
		ContextMoqParam       context.Context
		RetrieveSecretRequest *pb.RetrieveSecretRequest
	}{
		ContextMoqParam:       contextMoqParam,
		RetrieveSecretRequest: retrieveSecretRequest,
	}
	mock.lockRetrieveSecret.Lock()
	mock.calls.RetrieveSecret = append(mock.calls.RetrieveSecret, callInfo)
	mock.lockRetrieveSecret.Unlock()
	return mock.RetrieveSecretFunc(contextMoqParam, retrieveSecretRequest)
}

// RetrieveSecretCalls gets all the calls that were made to RetrieveSecret.
// Check the length with:
//
//	len(mockedKeeper.RetrieveSecretCalls())
func (mock *KeeperMock) RetrieveSecretCalls() []struct {
	ContextMoqParam       context.Context
	RetrieveSecretRequest *pb.RetrieveSecretRequest
} {
	var calls []struct {
		ContextMoqParam       context.Context
		RetrieveSecretRequest *pb.RetrieveSecretRequest
	}
	mock.lockRetrieveSecret.RLock()
	calls = mock.calls.RetrieveSecret
	mock.lockRetrieveSecret.RUnlock()
	return calls
}

// UploadFile calls UploadFileFunc.
func (mock *KeeperMock) UploadFile(clientStreamingServer grpc.ClientStreamingServer[httpbody.HttpBody, emptypb.Empty]) error {
	if mock.UploadFileFunc == nil {
		panic("KeeperMock.UploadFileFunc: method is nil but Keeper.UploadFile was just called")
	}
	callInfo := struct {
		ClientStreamingServer grpc.ClientStreamingServer[httpbody.HttpBody, emptypb.Empty]
	}{
		ClientStreamingServer: clientStreamingServer,
	}
	mock.lockUploadFile.Lock()
	mock.calls.UploadFile = append(mock.calls.UploadFile, callInfo)
	mock.lockUploadFile.Unlock()
	return mock.UploadFileFunc(clientStreamingServer)
}

// UploadFileCalls gets all the calls that were made to UploadFile.
// Check the length with:
//
//	len(mockedKeeper.UploadFileCalls())
func (mock *KeeperMock) UploadFileCalls() []struct {
	ClientStreamingServer grpc.ClientStreamingServer[httpbody.HttpBody, emptypb.Empty]
} {
	var calls []struct {
		ClientStreamingServer grpc.ClientStreamingServer[httpbody.HttpBody, emptypb.Empty]
	}
	mock.lockUploadFile.RLock()
	calls = mock.calls.UploadFile
	mock.lockUploadFile.RUnlock()
	return calls
}
