// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service

import (
	"context"
	"sync"
)

// Ensure, that KeeperMock does implement Keeper.
// If this is not the case, regenerate this file with moq.
var _ Keeper = &KeeperMock{}

// KeeperMock is a mock implementation of Keeper.
//
//	func TestSomethingThatUsesKeeper(t *testing.T) {
//
//		// make and configure a mocked Keeper
//		mockedKeeper := &KeeperMock{
//			DeleteDataFunc: func(ctx context.Context, in *DeleteDataRequest) (*DeleteDataResponse, error) {
//				panic("mock out the DeleteData method")
//			},
//			DownloadDataFunc: func(ctx context.Context, in *DownloadDataRequest) (*DownloadDataResponse, error) {
//				panic("mock out the DownloadData method")
//			},
//			ListDataFunc: func(ctx context.Context, in *ListDataRequest) (*ListDataResponse, error) {
//				panic("mock out the ListData method")
//			},
//			UploadDataFunc: func(ctx context.Context, in *UploadDataRequest) (*UploadDataResponse, error) {
//				panic("mock out the UploadData method")
//			},
//		}
//
//		// use mockedKeeper in code that requires Keeper
//		// and then make assertions.
//
//	}
type KeeperMock struct {
	// DeleteDataFunc mocks the DeleteData method.
	DeleteDataFunc func(ctx context.Context, in *DeleteDataRequest) (*DeleteDataResponse, error)

	// DownloadDataFunc mocks the DownloadData method.
	DownloadDataFunc func(ctx context.Context, in *DownloadDataRequest) (*DownloadDataResponse, error)

	// ListDataFunc mocks the ListData method.
	ListDataFunc func(ctx context.Context, in *ListDataRequest) (*ListDataResponse, error)

	// UploadDataFunc mocks the UploadData method.
	UploadDataFunc func(ctx context.Context, in *UploadDataRequest) (*UploadDataResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// DeleteData holds details about calls to the DeleteData method.
		DeleteData []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *DeleteDataRequest
		}
		// DownloadData holds details about calls to the DownloadData method.
		DownloadData []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *DownloadDataRequest
		}
		// ListData holds details about calls to the ListData method.
		ListData []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *ListDataRequest
		}
		// UploadData holds details about calls to the UploadData method.
		UploadData []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *UploadDataRequest
		}
	}
	lockDeleteData   sync.RWMutex
	lockDownloadData sync.RWMutex
	lockListData     sync.RWMutex
	lockUploadData   sync.RWMutex
}

// DeleteData calls DeleteDataFunc.
func (mock *KeeperMock) DeleteData(ctx context.Context, in *DeleteDataRequest) (*DeleteDataResponse, error) {
	if mock.DeleteDataFunc == nil {
		panic("KeeperMock.DeleteDataFunc: method is nil but Keeper.DeleteData was just called")
	}
	callInfo := struct {
		Ctx context.Context
		In  *DeleteDataRequest
	}{
		Ctx: ctx,
		In:  in,
	}
	mock.lockDeleteData.Lock()
	mock.calls.DeleteData = append(mock.calls.DeleteData, callInfo)
	mock.lockDeleteData.Unlock()
	return mock.DeleteDataFunc(ctx, in)
}

// DeleteDataCalls gets all the calls that were made to DeleteData.
// Check the length with:
//
//	len(mockedKeeper.DeleteDataCalls())
func (mock *KeeperMock) DeleteDataCalls() []struct {
	Ctx context.Context
	In  *DeleteDataRequest
} {
	var calls []struct {
		Ctx context.Context
		In  *DeleteDataRequest
	}
	mock.lockDeleteData.RLock()
	calls = mock.calls.DeleteData
	mock.lockDeleteData.RUnlock()
	return calls
}

// DownloadData calls DownloadDataFunc.
func (mock *KeeperMock) DownloadData(ctx context.Context, in *DownloadDataRequest) (*DownloadDataResponse, error) {
	if mock.DownloadDataFunc == nil {
		panic("KeeperMock.DownloadDataFunc: method is nil but Keeper.DownloadData was just called")
	}
	callInfo := struct {
		Ctx context.Context
		In  *DownloadDataRequest
	}{
		Ctx: ctx,
		In:  in,
	}
	mock.lockDownloadData.Lock()
	mock.calls.DownloadData = append(mock.calls.DownloadData, callInfo)
	mock.lockDownloadData.Unlock()
	return mock.DownloadDataFunc(ctx, in)
}

// DownloadDataCalls gets all the calls that were made to DownloadData.
// Check the length with:
//
//	len(mockedKeeper.DownloadDataCalls())
func (mock *KeeperMock) DownloadDataCalls() []struct {
	Ctx context.Context
	In  *DownloadDataRequest
} {
	var calls []struct {
		Ctx context.Context
		In  *DownloadDataRequest
	}
	mock.lockDownloadData.RLock()
	calls = mock.calls.DownloadData
	mock.lockDownloadData.RUnlock()
	return calls
}

// ListData calls ListDataFunc.
func (mock *KeeperMock) ListData(ctx context.Context, in *ListDataRequest) (*ListDataResponse, error) {
	if mock.ListDataFunc == nil {
		panic("KeeperMock.ListDataFunc: method is nil but Keeper.ListData was just called")
	}
	callInfo := struct {
		Ctx context.Context
		In  *ListDataRequest
	}{
		Ctx: ctx,
		In:  in,
	}
	mock.lockListData.Lock()
	mock.calls.ListData = append(mock.calls.ListData, callInfo)
	mock.lockListData.Unlock()
	return mock.ListDataFunc(ctx, in)
}

// ListDataCalls gets all the calls that were made to ListData.
// Check the length with:
//
//	len(mockedKeeper.ListDataCalls())
func (mock *KeeperMock) ListDataCalls() []struct {
	Ctx context.Context
	In  *ListDataRequest
} {
	var calls []struct {
		Ctx context.Context
		In  *ListDataRequest
	}
	mock.lockListData.RLock()
	calls = mock.calls.ListData
	mock.lockListData.RUnlock()
	return calls
}

// UploadData calls UploadDataFunc.
func (mock *KeeperMock) UploadData(ctx context.Context, in *UploadDataRequest) (*UploadDataResponse, error) {
	if mock.UploadDataFunc == nil {
		panic("KeeperMock.UploadDataFunc: method is nil but Keeper.UploadData was just called")
	}
	callInfo := struct {
		Ctx context.Context
		In  *UploadDataRequest
	}{
		Ctx: ctx,
		In:  in,
	}
	mock.lockUploadData.Lock()
	mock.calls.UploadData = append(mock.calls.UploadData, callInfo)
	mock.lockUploadData.Unlock()
	return mock.UploadDataFunc(ctx, in)
}

// UploadDataCalls gets all the calls that were made to UploadData.
// Check the length with:
//
//	len(mockedKeeper.UploadDataCalls())
func (mock *KeeperMock) UploadDataCalls() []struct {
	Ctx context.Context
	In  *UploadDataRequest
} {
	var calls []struct {
		Ctx context.Context
		In  *UploadDataRequest
	}
	mock.lockUploadData.RLock()
	calls = mock.calls.UploadData
	mock.lockUploadData.RUnlock()
	return calls
}
