// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deleteSecretByID.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const deleteSecretByID = `-- name: DeleteSecretByID :exec
DELETE FROM deposited_secrets WHERE depositor_pub_key_id = $1 AND id = $2
`

type DeleteSecretByIDParams struct {
	DepositorPubKeyID uuid.UUID
	ID                uuid.UUID
}

func (q *Queries) DeleteSecretByID(ctx context.Context, arg DeleteSecretByIDParams) error {
	_, err := q.db.Exec(ctx, deleteSecretByID, arg.DepositorPubKeyID, arg.ID)
	return err
}
