// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insertDepositedDatum.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const insertDepositedSecret = `-- name: InsertDepositedSecret :one
INSERT INTO
  deposited_secrets (id, depositor_pub_key_id, encrypted_data)
VALUES
  ($1, $2, $3)
RETURNING
  id, depositor_pub_key_id, encrypted_data
`

type InsertDepositedSecretParams struct {
	ID                uuid.UUID
	DepositorPubKeyID uuid.UUID
	EncryptedData     []byte
}

func (q *Queries) InsertDepositedSecret(ctx context.Context, arg InsertDepositedSecretParams) (DepositedSecret, error) {
	row := q.db.QueryRow(ctx, insertDepositedSecret, arg.ID, arg.DepositorPubKeyID, arg.EncryptedData)
	var i DepositedSecret
	err := row.Scan(&i.ID, &i.DepositorPubKeyID, &i.EncryptedData)
	return i, err
}
