// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insertRefreshToken.sql

package queries

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO
  depositor_refresh_tokens (token, depositor_pub_key_id, revoked_at)
VALUES
  ($1, $2, $3)
`

type InsertRefreshTokenParams struct {
	Token             uuid.UUID
	DepositorPubKeyID uuid.UUID
	RevokedAt         sql.NullTime
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken, arg.Token, arg.DepositorPubKeyID, arg.RevokedAt)
	return err
}
