// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insertRefreshToken.sql

package queries

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO
  depositor_refresh_tokens (
    id,
    token,
    depositor_pub_key_id,
    issued_at,
    revoked_at
  )
VALUES
  ($1, $2, $3, $4, $5)
`

type InsertRefreshTokenParams struct {
	ID                uuid.UUID
	Token             string
	DepositorPubKeyID uuid.UUID
	IssuedAt          time.Time
	RevokedAt         sql.NullTime
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken,
		arg.ID,
		arg.Token,
		arg.DepositorPubKeyID,
		arg.IssuedAt,
		arg.RevokedAt,
	)
	return err
}
