// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insertRefreshToken.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertRefreshToken = `-- name: InsertRefreshToken :one
INSERT INTO
  depositor_refresh_tokens (
    id,
    token,
    depositor_pub_key_id,
    issued_at,
    revoked_at
  )
VALUES
  ($1, $2, $3, $4, $5)
RETURNING
  id,
  token,
  depositor_pub_key_id
`

type InsertRefreshTokenParams struct {
	ID                pgtype.UUID
	Token             string
	DepositorPubKeyID pgtype.UUID
	IssuedAt          pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
}

type InsertRefreshTokenRow struct {
	ID                pgtype.UUID
	Token             string
	DepositorPubKeyID pgtype.UUID
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (InsertRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, insertRefreshToken,
		arg.ID,
		arg.Token,
		arg.DepositorPubKeyID,
		arg.IssuedAt,
		arg.RevokedAt,
	)
	var i InsertRefreshTokenRow
	err := row.Scan(&i.ID, &i.Token, &i.DepositorPubKeyID)
	return i, err
}
