// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insertPubKey.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const insertPubKey = `-- name: InsertPubKey :exec
INSERT INTO
  depositor_pub_keys (id, pub_key)
VALUES
  ($1, $2)
`

type InsertPubKeyParams struct {
	ID     uuid.UUID
	PubKey string
}

func (q *Queries) InsertPubKey(ctx context.Context, arg InsertPubKeyParams) error {
	_, err := q.db.Exec(ctx, insertPubKey, arg.ID, arg.PubKey)
	return err
}
