// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/google/uuid"
)

type DepositedDatum struct {
	ID                uuid.UUID
	DepositorPubKeyID uuid.UUID
	EncryptedData     []byte
}

// depositor_pub_keys are the registered public keys of depositors
type DepositorPubKey struct {
	// id is a UUID v7 value. It includes the timestamp at which the pub_key was registered
	ID     uuid.UUID
	PubKey string
}
