// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type DepositedDatum struct {
	ID                uuid.UUID
	DepositorPubKeyID uuid.UUID
	CipheredData      []byte
}

type DepositorApp struct {
	ID                uuid.UUID
	AppName           string
	DepositorPubKeyID uuid.UUID
}

type DepositorAppSession struct {
	ID             uuid.UUID
	DepositorAppID uuid.UUID
	StartedAt      time.Time
	ExpiredAt      sql.NullTime
}

type DepositorPubKey struct {
	ID     uuid.UUID
	PubKey string
}

type DepositorRefreshToken struct {
	ID                uuid.UUID
	Token             string
	DepositorPubKeyID uuid.UUID
	IssuedAt          time.Time
	RevokedAt         sql.NullTime
}
