// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DepositedDatum struct {
	ID                pgtype.UUID
	DepositorPubKeyID pgtype.UUID
	CipheredData      []byte
}

type DepositorApp struct {
	ID                pgtype.UUID
	AppName           string
	DepositorPubKeyID pgtype.UUID
}

type DepositorAppSession struct {
	ID             pgtype.UUID
	DepositorAppID pgtype.UUID
	StartedAt      pgtype.Timestamptz
	ExpiredAt      pgtype.Timestamptz
}

type DepositorPubKey struct {
	ID     pgtype.UUID
	PubKey string
}

type DepositorRefreshToken struct {
	ID                pgtype.UUID
	Token             string
	DepositorPubKeyID pgtype.UUID
	IssuedAt          pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
}
