// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: selectDepositedSecretData.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const selectDepositedSecretData = `-- name: SelectDepositedSecretData :one
SELECT encrypted_data FROM deposited_secrets WHERE id = $1
`

func (q *Queries) SelectDepositedSecretData(ctx context.Context, id uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, selectDepositedSecretData, id)
	var encrypted_data []byte
	err := row.Scan(&encrypted_data)
	return encrypted_data, err
}
