// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: selectDepositedSecretIDs.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const selectDepositedSecretIDs = `-- name: SelectDepositedSecretIDs :many
SELECT id FROM deposited_secrets WHERE depositor_pub_key_id = $1
`

func (q *Queries) SelectDepositedSecretIDs(ctx context.Context, depositorPubKeyID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, selectDepositedSecretIDs, depositorPubKeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
