// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: selectPubKeyID.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const selectPubKeyByID = `-- name: SelectPubKeyByID :one
SELECT
  id, pub_key
FROM
  depositor_pub_keys
WHERE
  id = $1
`

func (q *Queries) SelectPubKeyByID(ctx context.Context, id uuid.UUID) (DepositorPubKey, error) {
	row := q.db.QueryRow(ctx, selectPubKeyByID, id)
	var i DepositorPubKey
	err := row.Scan(&i.ID, &i.PubKey)
	return i, err
}
