// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: selectDepositedSecretData.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const selectDepositedSecretData = `-- name: SelectDepositedSecretData :one
SELECT
  depositor_pub_key_id,
  encrypted_data
FROM
  deposited_secrets
WHERE
  id = $1
`

type SelectDepositedSecretDataRow struct {
	DepositorPubKeyID uuid.UUID
	EncryptedData     []byte
}

func (q *Queries) SelectDepositedSecretData(ctx context.Context, id uuid.UUID) (SelectDepositedSecretDataRow, error) {
	row := q.db.QueryRow(ctx, selectDepositedSecretData, id)
	var i SelectDepositedSecretDataRow
	err := row.Scan(&i.DepositorPubKeyID, &i.EncryptedData)
	return i, err
}
