// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package keeper

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/oleshko-g/gophkeeper/internal/db/pgx/queries"
)

// Ensure, that QuerierMock does implement Querier.
// If this is not the case, regenerate this file with moq.
var _ Querier = &QuerierMock{}

// QuerierMock is a mock implementation of Querier.
//
//	func TestSomethingThatUsesQuerier(t *testing.T) {
//
//		// make and configure a mocked Querier
//		mockedQuerier := &QuerierMock{
//			DeleteSecretByIDFunc: func(ctx context.Context, arg queries.DeleteSecretByIDParams) error {
//				panic("mock out the DeleteSecretByID method")
//			},
//			InsertDepositedSecretFunc: func(ctx context.Context, arg queries.InsertDepositedSecretParams) (queries.DepositedSecret, error) {
//				panic("mock out the InsertDepositedSecret method")
//			},
//			SelectDepositedSecretDataFunc: func(ctx context.Context, id uuid.UUID) (queries.SelectDepositedSecretDataRow, error) {
//				panic("mock out the SelectDepositedSecretData method")
//			},
//			SelectDepositedSecretIDsFunc: func(ctx context.Context, depositorPubKeyID uuid.UUID) ([]uuid.UUID, error) {
//				panic("mock out the SelectDepositedSecretIDs method")
//			},
//		}
//
//		// use mockedQuerier in code that requires Querier
//		// and then make assertions.
//
//	}
type QuerierMock struct {
	// DeleteSecretByIDFunc mocks the DeleteSecretByID method.
	DeleteSecretByIDFunc func(ctx context.Context, arg queries.DeleteSecretByIDParams) error

	// InsertDepositedSecretFunc mocks the InsertDepositedSecret method.
	InsertDepositedSecretFunc func(ctx context.Context, arg queries.InsertDepositedSecretParams) (queries.DepositedSecret, error)

	// SelectDepositedSecretDataFunc mocks the SelectDepositedSecretData method.
	SelectDepositedSecretDataFunc func(ctx context.Context, id uuid.UUID) (queries.SelectDepositedSecretDataRow, error)

	// SelectDepositedSecretIDsFunc mocks the SelectDepositedSecretIDs method.
	SelectDepositedSecretIDsFunc func(ctx context.Context, depositorPubKeyID uuid.UUID) ([]uuid.UUID, error)

	// calls tracks calls to the methods.
	calls struct {
		// DeleteSecretByID holds details about calls to the DeleteSecretByID method.
		DeleteSecretByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg queries.DeleteSecretByIDParams
		}
		// InsertDepositedSecret holds details about calls to the InsertDepositedSecret method.
		InsertDepositedSecret []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg queries.InsertDepositedSecretParams
		}
		// SelectDepositedSecretData holds details about calls to the SelectDepositedSecretData method.
		SelectDepositedSecretData []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// SelectDepositedSecretIDs holds details about calls to the SelectDepositedSecretIDs method.
		SelectDepositedSecretIDs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DepositorPubKeyID is the depositorPubKeyID argument value.
			DepositorPubKeyID uuid.UUID
		}
	}
	lockDeleteSecretByID          sync.RWMutex
	lockInsertDepositedSecret     sync.RWMutex
	lockSelectDepositedSecretData sync.RWMutex
	lockSelectDepositedSecretIDs  sync.RWMutex
}

// DeleteSecretByID calls DeleteSecretByIDFunc.
func (mock *QuerierMock) DeleteSecretByID(ctx context.Context, arg queries.DeleteSecretByIDParams) error {
	if mock.DeleteSecretByIDFunc == nil {
		panic("QuerierMock.DeleteSecretByIDFunc: method is nil but Querier.DeleteSecretByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg queries.DeleteSecretByIDParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockDeleteSecretByID.Lock()
	mock.calls.DeleteSecretByID = append(mock.calls.DeleteSecretByID, callInfo)
	mock.lockDeleteSecretByID.Unlock()
	return mock.DeleteSecretByIDFunc(ctx, arg)
}

// DeleteSecretByIDCalls gets all the calls that were made to DeleteSecretByID.
// Check the length with:
//
//	len(mockedQuerier.DeleteSecretByIDCalls())
func (mock *QuerierMock) DeleteSecretByIDCalls() []struct {
	Ctx context.Context
	Arg queries.DeleteSecretByIDParams
} {
	var calls []struct {
		Ctx context.Context
		Arg queries.DeleteSecretByIDParams
	}
	mock.lockDeleteSecretByID.RLock()
	calls = mock.calls.DeleteSecretByID
	mock.lockDeleteSecretByID.RUnlock()
	return calls
}

// InsertDepositedSecret calls InsertDepositedSecretFunc.
func (mock *QuerierMock) InsertDepositedSecret(ctx context.Context, arg queries.InsertDepositedSecretParams) (queries.DepositedSecret, error) {
	if mock.InsertDepositedSecretFunc == nil {
		panic("QuerierMock.InsertDepositedSecretFunc: method is nil but Querier.InsertDepositedSecret was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg queries.InsertDepositedSecretParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockInsertDepositedSecret.Lock()
	mock.calls.InsertDepositedSecret = append(mock.calls.InsertDepositedSecret, callInfo)
	mock.lockInsertDepositedSecret.Unlock()
	return mock.InsertDepositedSecretFunc(ctx, arg)
}

// InsertDepositedSecretCalls gets all the calls that were made to InsertDepositedSecret.
// Check the length with:
//
//	len(mockedQuerier.InsertDepositedSecretCalls())
func (mock *QuerierMock) InsertDepositedSecretCalls() []struct {
	Ctx context.Context
	Arg queries.InsertDepositedSecretParams
} {
	var calls []struct {
		Ctx context.Context
		Arg queries.InsertDepositedSecretParams
	}
	mock.lockInsertDepositedSecret.RLock()
	calls = mock.calls.InsertDepositedSecret
	mock.lockInsertDepositedSecret.RUnlock()
	return calls
}

// SelectDepositedSecretData calls SelectDepositedSecretDataFunc.
func (mock *QuerierMock) SelectDepositedSecretData(ctx context.Context, id uuid.UUID) (queries.SelectDepositedSecretDataRow, error) {
	if mock.SelectDepositedSecretDataFunc == nil {
		panic("QuerierMock.SelectDepositedSecretDataFunc: method is nil but Querier.SelectDepositedSecretData was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockSelectDepositedSecretData.Lock()
	mock.calls.SelectDepositedSecretData = append(mock.calls.SelectDepositedSecretData, callInfo)
	mock.lockSelectDepositedSecretData.Unlock()
	return mock.SelectDepositedSecretDataFunc(ctx, id)
}

// SelectDepositedSecretDataCalls gets all the calls that were made to SelectDepositedSecretData.
// Check the length with:
//
//	len(mockedQuerier.SelectDepositedSecretDataCalls())
func (mock *QuerierMock) SelectDepositedSecretDataCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockSelectDepositedSecretData.RLock()
	calls = mock.calls.SelectDepositedSecretData
	mock.lockSelectDepositedSecretData.RUnlock()
	return calls
}

// SelectDepositedSecretIDs calls SelectDepositedSecretIDsFunc.
func (mock *QuerierMock) SelectDepositedSecretIDs(ctx context.Context, depositorPubKeyID uuid.UUID) ([]uuid.UUID, error) {
	if mock.SelectDepositedSecretIDsFunc == nil {
		panic("QuerierMock.SelectDepositedSecretIDsFunc: method is nil but Querier.SelectDepositedSecretIDs was just called")
	}
	callInfo := struct {
		Ctx               context.Context
		DepositorPubKeyID uuid.UUID
	}{
		Ctx:               ctx,
		DepositorPubKeyID: depositorPubKeyID,
	}
	mock.lockSelectDepositedSecretIDs.Lock()
	mock.calls.SelectDepositedSecretIDs = append(mock.calls.SelectDepositedSecretIDs, callInfo)
	mock.lockSelectDepositedSecretIDs.Unlock()
	return mock.SelectDepositedSecretIDsFunc(ctx, depositorPubKeyID)
}

// SelectDepositedSecretIDsCalls gets all the calls that were made to SelectDepositedSecretIDs.
// Check the length with:
//
//	len(mockedQuerier.SelectDepositedSecretIDsCalls())
func (mock *QuerierMock) SelectDepositedSecretIDsCalls() []struct {
	Ctx               context.Context
	DepositorPubKeyID uuid.UUID
} {
	var calls []struct {
		Ctx               context.Context
		DepositorPubKeyID uuid.UUID
	}
	mock.lockSelectDepositedSecretIDs.RLock()
	calls = mock.calls.SelectDepositedSecretIDs
	mock.lockSelectDepositedSecretIDs.RUnlock()
	return calls
}
