// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package keeper

// Ensure, that QuerierMock does implement Querier.
// If this is not the case, regenerate this file with moq.
var _ Querier = &QuerierMock{}

// QuerierMock is a mock implementation of Querier.
//
//	func TestSomethingThatUsesQuerier(t *testing.T) {
//
//		// make and configure a mocked Querier
//		mockedQuerier := &QuerierMock{
//		}
//
//		// use mockedQuerier in code that requires Querier
//		// and then make assertions.
//
//	}
type QuerierMock struct {
	// calls tracks calls to the methods.
	calls struct {
	}
}
