// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: v1/api.proto

package keeper_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientAppService_Register_FullMethodName  = "/gophkeper.v1.ClientAppService/Register"
	ClientAppService_Authorize_FullMethodName = "/gophkeper.v1.ClientAppService/Authorize"
	ClientAppService_Connect_FullMethodName   = "/gophkeper.v1.ClientAppService/Connect"
)

// ClientAppServiceClient is the client API for ClientAppService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClientAppService is the interface to:
//   - [Register] public keys of the Keeper users
//   - [Authorize] their client apps
//   - and [Connect] through the authorized apps to [KeeperService]
type ClientAppServiceClient interface {
	// Register registers an anonymous public key and returns a refresh token.
	// The owner of the refresh token can then [Authorize] apps to [Connect] to [KeeperService]
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Authorize authorizes an app to [Connect] to [KeeperService] and returns an authentication token.
	// The owner of the authentication token can then [Connect] to [KeeperService]
	Authorize(ctx context.Context, in *AuthorizeRequest, opts ...grpc.CallOption) (*AuthorizeResponse, error)
	// Connect creates a new [Session] for an [Authorize]d client app.
	// The holder of the session can then make requests to [KeeperService]
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
}

type clientAppServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientAppServiceClient(cc grpc.ClientConnInterface) ClientAppServiceClient {
	return &clientAppServiceClient{cc}
}

func (c *clientAppServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, ClientAppService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientAppServiceClient) Authorize(ctx context.Context, in *AuthorizeRequest, opts ...grpc.CallOption) (*AuthorizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizeResponse)
	err := c.cc.Invoke(ctx, ClientAppService_Authorize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientAppServiceClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, ClientAppService_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientAppServiceServer is the server API for ClientAppService service.
// All implementations must embed UnimplementedClientAppServiceServer
// for forward compatibility.
//
// ClientAppService is the interface to:
//   - [Register] public keys of the Keeper users
//   - [Authorize] their client apps
//   - and [Connect] through the authorized apps to [KeeperService]
type ClientAppServiceServer interface {
	// Register registers an anonymous public key and returns a refresh token.
	// The owner of the refresh token can then [Authorize] apps to [Connect] to [KeeperService]
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Authorize authorizes an app to [Connect] to [KeeperService] and returns an authentication token.
	// The owner of the authentication token can then [Connect] to [KeeperService]
	Authorize(context.Context, *AuthorizeRequest) (*AuthorizeResponse, error)
	// Connect creates a new [Session] for an [Authorize]d client app.
	// The holder of the session can then make requests to [KeeperService]
	Connect(context.Context, *ConnectRequest) (*ConnectResponse, error)
	mustEmbedUnimplementedClientAppServiceServer()
}

// UnimplementedClientAppServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientAppServiceServer struct{}

func (UnimplementedClientAppServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedClientAppServiceServer) Authorize(context.Context, *AuthorizeRequest) (*AuthorizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authorize not implemented")
}
func (UnimplementedClientAppServiceServer) Connect(context.Context, *ConnectRequest) (*ConnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedClientAppServiceServer) mustEmbedUnimplementedClientAppServiceServer() {}
func (UnimplementedClientAppServiceServer) testEmbeddedByValue()                          {}

// UnsafeClientAppServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientAppServiceServer will
// result in compilation errors.
type UnsafeClientAppServiceServer interface {
	mustEmbedUnimplementedClientAppServiceServer()
}

func RegisterClientAppServiceServer(s grpc.ServiceRegistrar, srv ClientAppServiceServer) {
	// If the following call panics, it indicates UnimplementedClientAppServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientAppService_ServiceDesc, srv)
}

func _ClientAppService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientAppServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientAppService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientAppServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientAppService_Authorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientAppServiceServer).Authorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientAppService_Authorize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientAppServiceServer).Authorize(ctx, req.(*AuthorizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientAppService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientAppServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientAppService_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientAppServiceServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientAppService_ServiceDesc is the grpc.ServiceDesc for ClientAppService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientAppService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gophkeper.v1.ClientAppService",
	HandlerType: (*ClientAppServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _ClientAppService_Register_Handler,
		},
		{
			MethodName: "Authorize",
			Handler:    _ClientAppService_Authorize_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _ClientAppService_Connect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/api.proto",
}

const (
	KeeperService_UploadData_FullMethodName   = "/gophkeper.v1.KeeperService/UploadData"
	KeeperService_DownloadData_FullMethodName = "/gophkeper.v1.KeeperService/DownloadData"
	KeeperService_ListData_FullMethodName     = "/gophkeper.v1.KeeperService/ListData"
	KeeperService_DeleteData_FullMethodName   = "/gophkeper.v1.KeeperService/DeleteData"
)

// KeeperServiceClient is the client API for KeeperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KeeperService is the interface to:
//   - [UploadData] of the owners of the [Register]ed public keys
//   - [DownloadData] the uploaded data
//   - [ListData] the uploaded data
//   - [DeleteData] the uploaded data
type KeeperServiceClient interface {
	// UploadData uploads data of the owners of the [Register]ed public keys.
	UploadData(ctx context.Context, in *UploadDataRequest, opts ...grpc.CallOption) (*UploadDataResponse, error)
	// DownloadData downloads the [Upload]ed data
	DownloadData(ctx context.Context, in *DownloadDataRequest, opts ...grpc.CallOption) (*DownloadDataResponse, error)
	// DownloadData lists the [Upload]ed data
	ListData(ctx context.Context, in *ListDataRequest, opts ...grpc.CallOption) (*ListDataResponse, error)
	// Delete deletes the [Upload]ed data from the [KeeperService]
	DeleteData(ctx context.Context, in *DeleteDataRequest, opts ...grpc.CallOption) (*DeleteDataResponse, error)
}

type keeperServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeeperServiceClient(cc grpc.ClientConnInterface) KeeperServiceClient {
	return &keeperServiceClient{cc}
}

func (c *keeperServiceClient) UploadData(ctx context.Context, in *UploadDataRequest, opts ...grpc.CallOption) (*UploadDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadDataResponse)
	err := c.cc.Invoke(ctx, KeeperService_UploadData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperServiceClient) DownloadData(ctx context.Context, in *DownloadDataRequest, opts ...grpc.CallOption) (*DownloadDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadDataResponse)
	err := c.cc.Invoke(ctx, KeeperService_DownloadData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperServiceClient) ListData(ctx context.Context, in *ListDataRequest, opts ...grpc.CallOption) (*ListDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDataResponse)
	err := c.cc.Invoke(ctx, KeeperService_ListData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperServiceClient) DeleteData(ctx context.Context, in *DeleteDataRequest, opts ...grpc.CallOption) (*DeleteDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDataResponse)
	err := c.cc.Invoke(ctx, KeeperService_DeleteData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeeperServiceServer is the server API for KeeperService service.
// All implementations must embed UnimplementedKeeperServiceServer
// for forward compatibility.
//
// KeeperService is the interface to:
//   - [UploadData] of the owners of the [Register]ed public keys
//   - [DownloadData] the uploaded data
//   - [ListData] the uploaded data
//   - [DeleteData] the uploaded data
type KeeperServiceServer interface {
	// UploadData uploads data of the owners of the [Register]ed public keys.
	UploadData(context.Context, *UploadDataRequest) (*UploadDataResponse, error)
	// DownloadData downloads the [Upload]ed data
	DownloadData(context.Context, *DownloadDataRequest) (*DownloadDataResponse, error)
	// DownloadData lists the [Upload]ed data
	ListData(context.Context, *ListDataRequest) (*ListDataResponse, error)
	// Delete deletes the [Upload]ed data from the [KeeperService]
	DeleteData(context.Context, *DeleteDataRequest) (*DeleteDataResponse, error)
	mustEmbedUnimplementedKeeperServiceServer()
}

// UnimplementedKeeperServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeeperServiceServer struct{}

func (UnimplementedKeeperServiceServer) UploadData(context.Context, *UploadDataRequest) (*UploadDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadData not implemented")
}
func (UnimplementedKeeperServiceServer) DownloadData(context.Context, *DownloadDataRequest) (*DownloadDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadData not implemented")
}
func (UnimplementedKeeperServiceServer) ListData(context.Context, *ListDataRequest) (*ListDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListData not implemented")
}
func (UnimplementedKeeperServiceServer) DeleteData(context.Context, *DeleteDataRequest) (*DeleteDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteData not implemented")
}
func (UnimplementedKeeperServiceServer) mustEmbedUnimplementedKeeperServiceServer() {}
func (UnimplementedKeeperServiceServer) testEmbeddedByValue()                       {}

// UnsafeKeeperServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeeperServiceServer will
// result in compilation errors.
type UnsafeKeeperServiceServer interface {
	mustEmbedUnimplementedKeeperServiceServer()
}

func RegisterKeeperServiceServer(s grpc.ServiceRegistrar, srv KeeperServiceServer) {
	// If the following call panics, it indicates UnimplementedKeeperServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeeperService_ServiceDesc, srv)
}

func _KeeperService_UploadData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).UploadData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_UploadData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).UploadData(ctx, req.(*UploadDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeeperService_DownloadData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).DownloadData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_DownloadData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).DownloadData(ctx, req.(*DownloadDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeeperService_ListData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).ListData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_ListData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).ListData(ctx, req.(*ListDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeeperService_DeleteData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).DeleteData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_DeleteData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).DeleteData(ctx, req.(*DeleteDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeeperService_ServiceDesc is the grpc.ServiceDesc for KeeperService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeeperService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gophkeper.v1.KeeperService",
	HandlerType: (*KeeperServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadData",
			Handler:    _KeeperService_UploadData_Handler,
		},
		{
			MethodName: "DownloadData",
			Handler:    _KeeperService_DownloadData_Handler,
		},
		{
			MethodName: "ListData",
			Handler:    _KeeperService_ListData_Handler,
		},
		{
			MethodName: "DeleteData",
			Handler:    _KeeperService_DeleteData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/api.proto",
}
